// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_pmhacc_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = sext <2 x i16> [[TMP2]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD_I]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhacc_i16x2(int16x2_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmhacc_i16x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhracc_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = sext <2 x i16> [[TMP2]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD6_I]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhracc_i16x2(int16x2_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmhracc_i16x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhaccu_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD_I]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmhaccu_u16x2(uint16x2_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhaccu_u16x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhraccu_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD6_I]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmhraccu_u16x2(uint16x2_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhraccu_u16x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhaccsu_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD_I]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhaccsu_i16x2(int16x2_t rd, int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhaccsu_i16x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhraccsu_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD6_I]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhraccsu_i16x2(int16x2_t rd, int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhraccsu_i16x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhacc_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = sext <4 x i16> [[TMP2]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[ADD_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmhacc_i16x4(int16x4_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmhacc_i16x4(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhracc_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = sext <4 x i16> [[TMP2]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <4 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[ADD6_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmhracc_i16x4(int16x4_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmhracc_i16x4(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhaccu_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <4 x i16> [[TMP2]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <4 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[ADD_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmhaccu_u16x4(uint16x4_t rd, uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmhaccu_u16x4(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhraccu_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <4 x i16> [[TMP2]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <4 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <4 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[ADD6_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmhraccu_u16x4(uint16x4_t rd, uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmhraccu_u16x4(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhaccsu_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <4 x i16> [[TMP2]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[ADD_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmhaccsu_i16x4(int16x4_t rd, int16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmhaccsu_i16x4(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhraccsu_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <4 x i16> [[TMP2]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <4 x i16> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[ADD6_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmhraccsu_i16x4(int16x4_t rd, int16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmhraccsu_i16x4(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhacc_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[CONV4_I:%.*]] = sext <2 x i32> [[TMP2]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[MUL_I]], splat (i64 32)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[ADD_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmhacc_i32x2(int32x2_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmhacc_i32x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhracc_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[CONV4_I:%.*]] = sext <2 x i32> [[TMP2]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i64> [[MUL_I]], splat (i64 2147483648)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[ADD_I]], splat (i64 32)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <2 x i32> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[ADD6_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmhracc_i32x2(int32x2_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmhracc_i32x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhaccu_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i32> [[TMP2]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i64> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[MUL_I]], splat (i64 32)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[ADD_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmhaccu_u32x2(uint32x2_t rd, uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmhaccu_u32x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhraccu_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i32> [[TMP2]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i64> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i64> [[MUL_I]], splat (i64 2147483648)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[ADD_I]], splat (i64 32)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <2 x i32> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[ADD6_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmhraccu_u32x2(uint32x2_t rd, uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmhraccu_u32x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhaccsu_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i32> [[TMP2]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[MUL_I]], splat (i64 32)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[ADD_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmhaccsu_i32x2(int32x2_t rd, int32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmhaccsu_i32x2(rd, rs1, rs2);
}

// RV64-LABEL: @test_pmhraccsu_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[CONV4_I:%.*]] = zext <2 x i32> [[TMP2]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV4_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i64> [[MUL_I]], splat (i64 2147483648)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[ADD_I]], splat (i64 32)
// RV64-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[ADD6_I:%.*]] = add <2 x i32> [[TMP0]], [[CONV5_I]]
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[ADD6_I]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmhraccsu_i32x2(int32x2_t rd, int32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmhraccsu_i32x2(rd, rs1, rs2);
}
