// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_pjoin4_i8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <4 x i8> poison, i8 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i8> [[TMP0]], i8 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = insertelement <4 x i8> [[TMP1]], i8 [[E2:%.*]], i64 2
// RV64-NEXT:    [[TMP3:%.*]] = insertelement <4 x i8> [[TMP2]], i8 [[E3:%.*]], i64 3
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
int8x4_t test_pjoin4_i8x4(int8_t e0, int8_t e1, int8_t e2, int8_t e3) {
  return __riscv_pjoin4_i8x4(e0, e1, e2, e3);
}
// RV64-LABEL: @test_pjoin4_u8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <4 x i8> poison, i8 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i8> [[TMP0]], i8 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = insertelement <4 x i8> [[TMP1]], i8 [[E2:%.*]], i64 2
// RV64-NEXT:    [[TMP3:%.*]] = insertelement <4 x i8> [[TMP2]], i8 [[E3:%.*]], i64 3
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t test_pjoin4_u8x4(uint8_t e0, uint8_t e1, uint8_t e2, uint8_t e3) {
  return __riscv_pjoin4_u8x4(e0, e1, e2, e3);
}
// RV64-LABEL: @test_pjoin2_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <2 x i16> poison, i16 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <2 x i16> [[TMP0]], i16 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int16x2_t test_pjoin2_i16x2(int16_t e0, int16_t e1) {
  return __riscv_pjoin2_i16x2(e0, e1);
}
// RV64-LABEL: @test_pjoin2_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <2 x i16> poison, i16 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <2 x i16> [[TMP0]], i16 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
uint16x2_t test_pjoin2_u16x2(uint16_t e0, uint16_t e1) {
  return __riscv_pjoin2_u16x2(e0, e1);
}

// RV64-LABEL: @test_pjoin4_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <4 x i16> poison, i16 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i16> [[TMP0]], i16 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = insertelement <4 x i16> [[TMP1]], i16 [[E2:%.*]], i64 2
// RV64-NEXT:    [[TMP3:%.*]] = insertelement <4 x i16> [[TMP2]], i16 [[E3:%.*]], i64 3
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int16x4_t test_pjoin4_i16x4(int16_t e0, int16_t e1, int16_t e2, int16_t e3) {
  return __riscv_pjoin4_i16x4(e0, e1, e2, e3);
}
// RV64-LABEL: @test_pjoin4_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <4 x i16> poison, i16 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i16> [[TMP0]], i16 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = insertelement <4 x i16> [[TMP1]], i16 [[E2:%.*]], i64 2
// RV64-NEXT:    [[TMP3:%.*]] = insertelement <4 x i16> [[TMP2]], i16 [[E3:%.*]], i64 3
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint16x4_t test_pjoin4_u16x4(uint16_t e0, uint16_t e1, uint16_t e2, uint16_t e3) {
  return __riscv_pjoin4_u16x4(e0, e1, e2, e3);
}
// RV64-LABEL: @test_pjoin2_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> poison, i32 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pjoin2_i32x2(int32_t e0, int32_t e1) {
  return __riscv_pjoin2_i32x2(e0, e1);
}
// RV64-LABEL: @test_pjoin2_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = insertelement <2 x i32> poison, i32 [[E0:%.*]], i64 0
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[E1:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pjoin2_u32x2(uint32_t e0, uint32_t e1) {
  return __riscv_pjoin2_u32x2(e0, e1);
}
