// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_pwunzipe_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.psext.h.b.v4i16.v8i8(<8 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwunzipe_i16x4(int8x8_t rs1) {
  return __riscv_pwunzipe_i16x4(rs1);
}
// RV64-LABEL: @test_pwunzipo_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = ashr <4 x i16> [[TMP0]], splat (i16 8)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwunzipo_i16x4(int8x8_t rs1) {
  return __riscv_pwunzipo_i16x4(rs1);
}
// RV64-LABEL: @test_pwunzipue_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.pnzip.v8i8.v4i16(<4 x i16> [[TMP0]], <4 x i16> zeroinitializer)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwunzipue_u16x4(uint8x8_t rs1) {
  return __riscv_pwunzipue_u16x4(rs1);
}
// RV64-LABEL: @test_pwunzipuo_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.pnziph.v8i8.v4i16(<4 x i16> [[TMP0]], <4 x i16> zeroinitializer)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwunzipuo_u16x4(uint8x8_t rs1) {
  return __riscv_pwunzipuo_u16x4(rs1);
}
// RV64-LABEL: @test_pwunziphe_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shl <4 x i16> [[TMP0]], splat (i16 8)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwunziphe_i16x4(int8x8_t rs1) {
  return __riscv_pwunziphe_i16x4(rs1);
}
// RV64-LABEL: @test_pwunzipho_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.pnziph.v8i8.v4i16(<4 x i16> zeroinitializer, <4 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwunzipho_i16x4(int8x8_t rs1) {
  return __riscv_pwunzipho_i16x4(rs1);
}
// RV64-LABEL: @test_pwunziphe_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shl <4 x i16> [[TMP0]], splat (i16 8)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwunziphe_u16x4(uint8x8_t rs1) {
  return __riscv_pwunziphe_u16x4(rs1);
}
// RV64-LABEL: @test_pwunzipho_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.pnziph.v8i8.v4i16(<4 x i16> zeroinitializer, <4 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwunzipho_u16x4(uint8x8_t rs1) {
  return __riscv_pwunzipho_u16x4(rs1);
}

// RV64-LABEL: @test_pwunzipe_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = call <2 x i32> @llvm.riscv.psext.w.h(<4 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwunzipe_i32x2(int16x4_t rs1) {
  return __riscv_pwunzipe_i32x2(rs1);
}
// RV64-LABEL: @test_pwunzipo_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = ashr <2 x i32> [[TMP0]], splat (i32 16)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwunzipo_i32x2(int16x4_t rs1) {
  return __riscv_pwunzipo_i32x2(rs1);
}
// RV64-LABEL: @test_pwunzipue_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.pnzip.v4i16.v2i32(<2 x i32> [[TMP0]], <2 x i32> zeroinitializer)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwunzipue_u32x2(uint16x4_t rs1) {
  return __riscv_pwunzipue_u32x2(rs1);
}
// RV64-LABEL: @test_pwunzipuo_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.pnziph.v4i16.v2i32(<2 x i32> [[TMP0]], <2 x i32> zeroinitializer)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwunzipuo_u32x2(uint16x4_t rs1) {
  return __riscv_pwunzipuo_u32x2(rs1);
}
// RV64-LABEL: @test_pwunziphe_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = shl <2 x i32> [[TMP0]], splat (i32 16)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwunziphe_i32x2(int16x4_t rs1) {
  return __riscv_pwunziphe_i32x2(rs1);
}
// RV64-LABEL: @test_pwunzipho_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.pnziph.v4i16.v2i32(<2 x i32> zeroinitializer, <2 x i32> [[TMP0]])
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwunzipho_i32x2(int16x4_t rs1) {
  return __riscv_pwunzipho_i32x2(rs1);
}
// RV64-LABEL: @test_pwunziphe_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = shl <2 x i32> [[TMP0]], splat (i32 16)
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwunziphe_u32x2(uint16x4_t rs1) {
  return __riscv_pwunziphe_u32x2(rs1);
}
// RV64-LABEL: @test_pwunzipho_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.pnziph.v4i16.v2i32(<2 x i32> zeroinitializer, <2 x i32> [[TMP0]])
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwunzipho_u32x2(uint16x4_t rs1) {
  return __riscv_pwunzipho_u32x2(rs1);
}
