// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pas_x_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pas.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pas_x_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pas_x_i16x2(rs1, rs2);
}

// RV32-LABEL: @test_psa_x_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.psa.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_psa_x_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_psa_x_i16x2(rs1, rs2);
}

// RV32-LABEL: @test_psas_x_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.psas.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_psas_x_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_psas_x_i16x2(rs1, rs2);
}

// RV32-LABEL: @test_pssa_x_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pssa.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pssa_x_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pssa_x_i16x2(rs1, rs2);
}

// RV32-LABEL: @test_paas_x_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.paas.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_paas_x_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_paas_x_i16x2(rs1, rs2);
}

// RV32-LABEL: @test_pasa_x_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pasa.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pasa_x_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pasa_x_i16x2(rs1, rs2);
}
