// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: define dso_local i32 @test_pmseq_i8x4_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0:[0-9]+]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmseq_i8x4_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmseq_i8x4_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmseq_u8x4_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmseq_u8x4_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmseq_u8x4_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmseq_i16x2_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmseq_i16x2_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmseq_i16x2_u16x2(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmseq_u16x2_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmseq_u16x2_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmseq_u16x2_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmslt_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmslt_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmslt_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmslt_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmslt_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmslt_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsgt_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmsgt_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsgt_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsgt_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmsgt_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsgt_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsltu_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmsltu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsltu_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsltu_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmsltu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsltu_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsgtu_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmsgtu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsgtu_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsgtu_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmsgtu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsgtu_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsne_i8x4_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsne_i8x4_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsne_i8x4_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsne_u8x4_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsne_u8x4_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsne_u8x4_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsne_i16x2_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsne_i16x2_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsne_i16x2_u16x2(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsne_u16x2_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsne_u16x2_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsne_u16x2_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsge_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsge_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsge_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsge_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsge_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsge_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsle_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsle_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsle_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsle_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsle_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsle_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsleu_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsleu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsleu_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsleu_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsleu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsleu_u16x2(rs1, rs2);
}

// RV32-LABEL: define dso_local i32 @test_pmsgeu_u8x4(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsgeu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsgeu_u8x4(rs1, rs2);
}
// RV32-LABEL: define dso_local i32 @test_pmsgeu_u16x2(
// RV32-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV32-NEXT:  [[ENTRY:.*:]]
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsgeu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsgeu_u16x2(rs1, rs2);
}
