// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

/* 32-bit table */
// RV32-LABEL: @test_pld_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i32, ptr [[P:%.*]], align 1
// RV32-NEXT:    ret i32 [[TMP0]]
//
int8x4_t test_pld_i8x4(int8_t *p) { return __riscv_pld_i8x4(p); }
// RV32-LABEL: @test_pld_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i32, ptr [[P:%.*]], align 1
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint8x4_t test_pld_u8x4(uint8_t *p) { return __riscv_pld_u8x4(p); }
// RV32-LABEL: @test_pld_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i32, ptr [[P:%.*]], align 2
// RV32-NEXT:    ret i32 [[TMP0]]
//
int16x2_t test_pld_i16x2(int16_t *p) { return __riscv_pld_i16x2(p); }
// RV32-LABEL: @test_pld_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i32, ptr [[P:%.*]], align 2
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint16x2_t test_pld_u16x2(uint16_t *p) { return __riscv_pld_u16x2(p); }
// RV32-LABEL: @test_pst_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i32 [[V_COERCE:%.*]], ptr [[P:%.*]], align 1
// RV32-NEXT:    ret void
//
void test_pst_i8x4(int8_t *p, int8x4_t v) { __riscv_pst_i8x4(p, v); }
// RV32-LABEL: @test_pst_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i32 [[V_COERCE:%.*]], ptr [[P:%.*]], align 1
// RV32-NEXT:    ret void
//
void test_pst_u8x4(uint8_t *p, uint8x4_t v) { __riscv_pst_u8x4(p, v); }
// RV32-LABEL: @test_pst_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i32 [[V_COERCE:%.*]], ptr [[P:%.*]], align 2
// RV32-NEXT:    ret void
//
void test_pst_i16x2(int16_t *p, int16x2_t v) { __riscv_pst_i16x2(p, v); }
// RV32-LABEL: @test_pst_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i32 [[V_COERCE:%.*]], ptr [[P:%.*]], align 2
// RV32-NEXT:    ret void
//
void test_pst_u16x2(uint16_t *p, uint16x2_t v) { __riscv_pst_u16x2(p, v); }

/* 64-bit table */
// RV32-LABEL: @test_pld_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i64, ptr [[P:%.*]], align 1
// RV32-NEXT:    ret i64 [[TMP0]]
//
int8x8_t test_pld_i8x8(int8_t *p) { return __riscv_pld_i8x8(p); }
// RV32-LABEL: @test_pld_u8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i64, ptr [[P:%.*]], align 1
// RV32-NEXT:    ret i64 [[TMP0]]
//
uint8x8_t test_pld_u8x8(uint8_t *p) { return __riscv_pld_u8x8(p); }
// RV32-LABEL: @test_pld_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i64, ptr [[P:%.*]], align 2
// RV32-NEXT:    ret i64 [[TMP0]]
//
int16x4_t test_pld_i16x4(int16_t *p) { return __riscv_pld_i16x4(p); }
// RV32-LABEL: @test_pld_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i64, ptr [[P:%.*]], align 2
// RV32-NEXT:    ret i64 [[TMP0]]
//
uint16x4_t test_pld_u16x4(uint16_t *p) { return __riscv_pld_u16x4(p); }
// RV32-LABEL: @test_pld_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i64, ptr [[P:%.*]], align 4
// RV32-NEXT:    ret i64 [[TMP0]]
//
int32x2_t test_pld_i32x2(int32_t *p) { return __riscv_pld_i32x2(p); }
// RV32-LABEL: @test_pld_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = load i64, ptr [[P:%.*]], align 4
// RV32-NEXT:    ret i64 [[TMP0]]
//
uint32x2_t test_pld_u32x2(uint32_t *p) { return __riscv_pld_u32x2(p); }
// RV32-LABEL: @test_pst_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i64 [[V_COERCE:%.*]], ptr [[P:%.*]], align 1
// RV32-NEXT:    ret void
//
void test_pst_i8x8(int8_t *p, int8x8_t v) { __riscv_pst_i8x8(p, v); }
// RV32-LABEL: @test_pst_u8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i64 [[V_COERCE:%.*]], ptr [[P:%.*]], align 1
// RV32-NEXT:    ret void
//
void test_pst_u8x8(uint8_t *p, uint8x8_t v) { __riscv_pst_u8x8(p, v); }
// RV32-LABEL: @test_pst_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i64 [[V_COERCE:%.*]], ptr [[P:%.*]], align 2
// RV32-NEXT:    ret void
//
void test_pst_i16x4(int16_t *p, int16x4_t v) { __riscv_pst_i16x4(p, v); }
// RV32-LABEL: @test_pst_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i64 [[V_COERCE:%.*]], ptr [[P:%.*]], align 2
// RV32-NEXT:    ret void
//
void test_pst_u16x4(uint16_t *p, uint16x4_t v) { __riscv_pst_u16x4(p, v); }
// RV32-LABEL: @test_pst_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i64 [[V_COERCE:%.*]], ptr [[P:%.*]], align 4
// RV32-NEXT:    ret void
//
void test_pst_i32x2(int32_t *p, int32x2_t v) { __riscv_pst_i32x2(p, v); }
// RV32-LABEL: @test_pst_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    store i64 [[V_COERCE:%.*]], ptr [[P:%.*]], align 4
// RV32-NEXT:    ret void
//
void test_pst_u32x2(uint32_t *p, uint32x2_t v) { __riscv_pst_u32x2(p, v); }
