// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// 32-bit-table forms — also available on RV64.

// RV64-LABEL: define dso_local i32 @test_pmseq_i8x4_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0:[0-9]+]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmseq_i8x4_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmseq_i8x4_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmseq_u8x4_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmseq_u8x4_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmseq_u8x4_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmseq_i16x2_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmseq_i16x2_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmseq_i16x2_u16x2(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmseq_u16x2_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmseq_u16x2_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmseq_u16x2_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmslt_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmslt_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmslt_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmslt_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmslt_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmslt_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsgt_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmsgt_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsgt_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsgt_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmsgt_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsgt_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsltu_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmsltu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsltu_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsltu_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmsltu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsltu_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsgtu_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t  test_pmsgtu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsgtu_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsgtu_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmsgtu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsgtu_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsne_i8x4_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsne_i8x4_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsne_i8x4_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsne_u8x4_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsne_u8x4_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsne_u8x4_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsne_i16x2_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsne_i16x2_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsne_i16x2_u16x2(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsne_u16x2_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsne_u16x2_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsne_u16x2_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsge_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsge_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsge_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsge_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsge_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsge_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsle_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsle_u8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmsle_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsle_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsle_u16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmsle_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsleu_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP1]], <4 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsleu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsleu_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsleu_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP1]], <2 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsleu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsleu_u16x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i32 @test_pmsgeu_u8x4(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint8x4_t  test_pmsgeu_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmsgeu_u8x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i32 @test_pmsgeu_u16x2(
// RV64-SAME: i32 noundef [[RS1_COERCE:%.*]], i32 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint16x2_t test_pmsgeu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmsgeu_u16x2(rs1, rs2);
}

// 64-bit-table forms — RV64-only.

// RV64-LABEL: define dso_local i64 @test_pmseq_i8x8_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmseq.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pmseq_i8x8_u8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmseq_i8x8_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmseq_u8x8_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmseq.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pmseq_u8x8_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmseq_u8x8_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmseq_i16x4_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmseq.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmseq_i16x4_u16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmseq_i16x4_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmseq_u16x4_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmseq.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmseq_u16x4_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmseq_u16x4_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmseq_i32x2_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmseq.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmseq_i32x2_u32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmseq_i32x2_u32x2(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmseq_u32x2_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmseq.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmseq_u32x2_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmseq_u32x2_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmslt_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmslt.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pmslt_u8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmslt_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmslt_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmslt.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmslt_u16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmslt_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmslt_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmslt.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmslt_u32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmslt_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsgt_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmslt.v8i8(<8 x i8> [[TMP1]], <8 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pmsgt_u8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmsgt_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsgt_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmslt.v4i16(<4 x i16> [[TMP1]], <4 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmsgt_u16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmsgt_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsgt_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmslt.v2i32(<2 x i32> [[TMP1]], <2 x i32> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmsgt_u32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmsgt_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsltu_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmsltu.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pmsltu_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmsltu_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsltu_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmsltu.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmsltu_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmsltu_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsltu_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmsltu.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmsltu_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmsltu_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsgtu_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmsltu.v8i8(<8 x i8> [[TMP1]], <8 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pmsgtu_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmsgtu_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsgtu_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmsltu.v4i16(<4 x i16> [[TMP1]], <4 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmsgtu_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmsgtu_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsgtu_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmsltu.v2i32(<2 x i32> [[TMP1]], <2 x i32> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmsgtu_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmsgtu_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsne_i8x8_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmseq.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <8 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint8x8_t  test_pmsne_i8x8_u8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmsne_i8x8_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsne_u8x8_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmseq.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <8 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint8x8_t  test_pmsne_u8x8_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmsne_u8x8_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsne_i16x4_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmseq.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint16x4_t test_pmsne_i16x4_u16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmsne_i16x4_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsne_u16x4_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmseq.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint16x4_t test_pmsne_u16x4_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmsne_u16x4_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsne_i32x2_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmseq.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i32> [[TMP2]], splat (i32 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint32x2_t test_pmsne_i32x2_u32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmsne_i32x2_u32x2(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsne_u32x2_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmseq.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i32> [[TMP2]], splat (i32 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint32x2_t test_pmsne_u32x2_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmsne_u32x2_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsge_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmslt.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <8 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint8x8_t  test_pmsge_u8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmsge_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsge_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmslt.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint16x4_t test_pmsge_u16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmsge_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsge_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmslt.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i32> [[TMP2]], splat (i32 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint32x2_t test_pmsge_u32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmsge_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsle_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmslt.v8i8(<8 x i8> [[TMP1]], <8 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <8 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint8x8_t  test_pmsle_u8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmsle_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsle_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmslt.v4i16(<4 x i16> [[TMP1]], <4 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint16x4_t test_pmsle_u16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmsle_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsle_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmslt.v2i32(<2 x i32> [[TMP1]], <2 x i32> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i32> [[TMP2]], splat (i32 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint32x2_t test_pmsle_u32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmsle_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsleu_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmsltu.v8i8(<8 x i8> [[TMP1]], <8 x i8> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <8 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint8x8_t  test_pmsleu_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmsleu_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsleu_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmsltu.v4i16(<4 x i16> [[TMP1]], <4 x i16> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint16x4_t test_pmsleu_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmsleu_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsleu_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmsltu.v2i32(<2 x i32> [[TMP1]], <2 x i32> [[TMP0]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i32> [[TMP2]], splat (i32 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint32x2_t test_pmsleu_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmsleu_u32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pmsgeu_u8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pmsltu.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <8 x i8> [[TMP2]], splat (i8 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <8 x i8> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint8x8_t  test_pmsgeu_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmsgeu_u8x8(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsgeu_u16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmsltu.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <4 x i16> [[TMP2]], splat (i16 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint16x4_t test_pmsgeu_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmsgeu_u16x4(rs1, rs2);
}
// RV64-LABEL: define dso_local i64 @test_pmsgeu_u32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmsltu.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = xor <2 x i32> [[TMP2]], splat (i32 -1)
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
uint32x2_t test_pmsgeu_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmsgeu_u32x2(rs1, rs2);
}
