// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=mem2reg,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_ssha_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.ssha.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_ssha_i32(int32_t a, int b)   { return __riscv_ssha_i32(a, b); }
// RV64-LABEL: @test_sshar_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.sshar.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_sshar_i32(int32_t a, int b)  { return __riscv_sshar_i32(a, b); }
// RV64-LABEL: @test_sshl_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.sshl.u32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_sshl_u32(int32_t a, int b)   { return __riscv_sshl_u32(a, b); }
// RV64-LABEL: @test_sshlr_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.sshlr.u32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_sshlr_u32(int32_t a, int b)  { return __riscv_sshlr_u32(a, b); }

// RV64-LABEL: @test_sha_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.sha.i64(i64 [[A:%.*]], i64 [[TMP0]])
// RV64-NEXT:    ret i64 [[TMP1]]
//
int64_t  test_sha_i64(int64_t a, int b)    { return __riscv_sha_i64(a, b); }
// RV64-LABEL: @test_shar_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.shar.i64(i64 [[A:%.*]], i64 [[TMP0]])
// RV64-NEXT:    ret i64 [[TMP1]]
//
int64_t  test_shar_i64(int64_t a, int b)   { return __riscv_shar_i64(a, b); }
// RV64-LABEL: @test_shl_u64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.shl.u64(i64 [[A:%.*]], i64 [[TMP0]])
// RV64-NEXT:    ret i64 [[TMP1]]
//
uint64_t test_shl_u64(uint64_t a, int b)   { return __riscv_shl_u64(a, b); }
// RV64-LABEL: @test_shlr_u64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.shlr.u64(i64 [[A:%.*]], i64 [[TMP0]])
// RV64-NEXT:    ret i64 [[TMP1]]
//
uint64_t test_shlr_u64(uint64_t a, int b)  { return __riscv_shlr_u64(a, b); }
