// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pmqwacc_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[A_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[B_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqwacc.v2i16(i64 [[RD_COERCE:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pmqwacc_i32x2(int32x2_t rd, int16x2_t a, int16x2_t b) {
  return __riscv_pmqwacc_i32x2(rd, a, b);
}

// RV32-LABEL: @test_pmqrwacc_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[A_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[B_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqrwacc.v2i16(i64 [[RD_COERCE:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pmqrwacc_i32x2(int32x2_t rd, int16x2_t a, int16x2_t b) {
  return __riscv_pmqrwacc_i32x2(rd, a, b);
}
