// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

/* 32-bit table */
// RV32-LABEL: @test_pslide1up_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = shl i32 [[RD_COERCE:%.*]], 8
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i32 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i32 [[TMP2]]
//
int8x4_t   test_pslide1up_i8x4(int8x4_t rd, int8_t rs1)     { return __riscv_pslide1up_i8x4(rd, rs1); }
// RV32-LABEL: @test_pslide1up_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = shl i32 [[RD_COERCE:%.*]], 8
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i32 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint8x4_t  test_pslide1up_u8x4(uint8x4_t rd, uint8_t rs1)   { return __riscv_pslide1up_u8x4(rd, rs1); }
// RV32-LABEL: @test_pslide1up_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = shl i32 [[RD_COERCE:%.*]], 16
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i32 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i32 [[TMP2]]
//
int16x2_t  test_pslide1up_i16x2(int16x2_t rd, int16_t rs1)  { return __riscv_pslide1up_i16x2(rd, rs1); }
// RV32-LABEL: @test_pslide1up_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = shl i32 [[RD_COERCE:%.*]], 16
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i32 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint16x2_t test_pslide1up_u16x2(uint16x2_t rd, uint16_t rs1) { return __riscv_pslide1up_u16x2(rd, rs1); }
// RV32-LABEL: @test_pslide1down_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[TMP0]], i32 [[RD_COERCE:%.*]], i32 24)
// RV32-NEXT:    ret i32 [[TMP1]]
//
int8x4_t   test_pslide1down_i8x4(int8x4_t rd, int8_t rs1)     { return __riscv_pslide1down_i8x4(rd, rs1); }
// RV32-LABEL: @test_pslide1down_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[TMP0]], i32 [[RD_COERCE:%.*]], i32 24)
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint8x4_t  test_pslide1down_u8x4(uint8x4_t rd, uint8_t rs1)   { return __riscv_pslide1down_u8x4(rd, rs1); }
// RV32-LABEL: @test_pslide1down_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[TMP0]], i32 [[RD_COERCE:%.*]], i32 16)
// RV32-NEXT:    ret i32 [[TMP1]]
//
int16x2_t  test_pslide1down_i16x2(int16x2_t rd, int16_t rs1)  { return __riscv_pslide1down_i16x2(rd, rs1); }
// RV32-LABEL: @test_pslide1down_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i32
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[TMP0]], i32 [[RD_COERCE:%.*]], i32 16)
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint16x2_t test_pslide1down_u16x2(uint16x2_t rd, uint16_t rs1) { return __riscv_pslide1down_u16x2(rd, rs1); }

/* 64-bit table */
// RV32-LABEL: @test_pslide1up_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = shl i64 [[RD_COERCE:%.*]], 8
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i64 [[TMP2]]
//
int8x8_t   test_pslide1up_i8x8(int8x8_t rd, int8_t rs1)     { return __riscv_pslide1up_i8x8(rd, rs1); }
// RV32-LABEL: @test_pslide1up_u8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = shl i64 [[RD_COERCE:%.*]], 8
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint8x8_t  test_pslide1up_u8x8(uint8x8_t rd, uint8_t rs1)   { return __riscv_pslide1up_u8x8(rd, rs1); }
// RV32-LABEL: @test_pslide1up_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = shl i64 [[RD_COERCE:%.*]], 16
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t  test_pslide1up_i16x4(int16x4_t rd, int16_t rs1)  { return __riscv_pslide1up_i16x4(rd, rs1); }
// RV32-LABEL: @test_pslide1up_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = shl i64 [[RD_COERCE:%.*]], 16
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pslide1up_u16x4(uint16x4_t rd, uint16_t rs1) { return __riscv_pslide1up_u16x4(rd, rs1); }
// RV32-LABEL: @test_pslide1up_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i32 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = shl i64 [[RD_COERCE:%.*]], 32
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t  test_pslide1up_i32x2(int32x2_t rd, int32_t rs1)  { return __riscv_pslide1up_i32x2(rd, rs1); }
// RV32-LABEL: @test_pslide1up_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i32 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = shl i64 [[RD_COERCE:%.*]], 32
// RV32-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pslide1up_u32x2(uint32x2_t rd, uint32_t rs1) { return __riscv_pslide1up_u32x2(rd, rs1); }
// RV32-LABEL: @test_pslide1down_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.fshl.i64(i64 [[TMP0]], i64 [[RD_COERCE:%.*]], i64 56)
// RV32-NEXT:    ret i64 [[TMP1]]
//
int8x8_t   test_pslide1down_i8x8(int8x8_t rd, int8_t rs1)     { return __riscv_pslide1down_i8x8(rd, rs1); }
// RV32-LABEL: @test_pslide1down_u8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i8 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.fshl.i64(i64 [[TMP0]], i64 [[RD_COERCE:%.*]], i64 56)
// RV32-NEXT:    ret i64 [[TMP1]]
//
uint8x8_t  test_pslide1down_u8x8(uint8x8_t rd, uint8_t rs1)   { return __riscv_pslide1down_u8x8(rd, rs1); }
// RV32-LABEL: @test_pslide1down_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.fshl.i64(i64 [[TMP0]], i64 [[RD_COERCE:%.*]], i64 48)
// RV32-NEXT:    ret i64 [[TMP1]]
//
int16x4_t  test_pslide1down_i16x4(int16x4_t rd, int16_t rs1)  { return __riscv_pslide1down_i16x4(rd, rs1); }
// RV32-LABEL: @test_pslide1down_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i16 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.fshl.i64(i64 [[TMP0]], i64 [[RD_COERCE:%.*]], i64 48)
// RV32-NEXT:    ret i64 [[TMP1]]
//
uint16x4_t test_pslide1down_u16x4(uint16x4_t rd, uint16_t rs1) { return __riscv_pslide1down_u16x4(rd, rs1); }
// RV32-LABEL: @test_pslide1down_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i32 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.fshl.i64(i64 [[TMP0]], i64 [[RD_COERCE:%.*]], i64 32)
// RV32-NEXT:    ret i64 [[TMP1]]
//
int32x2_t  test_pslide1down_i32x2(int32x2_t rd, int32_t rs1)  { return __riscv_pslide1down_i32x2(rd, rs1); }
// RV32-LABEL: @test_pslide1down_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = zext i32 [[RS1:%.*]] to i64
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.fshl.i64(i64 [[TMP0]], i64 [[RD_COERCE:%.*]], i64 32)
// RV32-NEXT:    ret i64 [[TMP1]]
//
uint32x2_t test_pslide1down_u32x2(uint32x2_t rd, uint32_t rs1) { return __riscv_pslide1down_u32x2(rd, rs1); }
