// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pwsll_s_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.pwsll.v4i8(<4 x i8> [[TMP0]], i32 [[SHAMT:%.*]])
// RV32-NEXT:    ret i64 [[TMP1]]
//
uint16x4_t test_pwsll_s_u16x4(uint8x4_t rs1, unsigned shamt) {
  return __riscv_pwsll_s_u16x4(rs1, shamt);
}

// RV32-LABEL: @test_pwsll_s_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.pwsll.v2i16(<2 x i16> [[TMP0]], i32 [[SHAMT:%.*]])
// RV32-NEXT:    ret i64 [[TMP1]]
//
uint32x2_t test_pwsll_s_u32x2(uint16x2_t rs1, unsigned shamt) {
  return __riscv_pwsll_s_u32x2(rs1, shamt);
}

// RV32-LABEL: @test_pwsla_s_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.pwsla.v4i8(<4 x i8> [[TMP0]], i32 [[SHAMT:%.*]])
// RV32-NEXT:    ret i64 [[TMP1]]
//
int16x4_t test_pwsla_s_i16x4(int8x4_t rs1, unsigned shamt) {
  return __riscv_pwsla_s_i16x4(rs1, shamt);
}

// RV32-LABEL: @test_pwsla_s_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.pwsla.v2i16(<2 x i16> [[TMP0]], i32 [[SHAMT:%.*]])
// RV32-NEXT:    ret i64 [[TMP1]]
//
int32x2_t test_pwsla_s_i32x2(int16x2_t rs1, unsigned shamt) {
  return __riscv_pwsla_s_i32x2(rs1, shamt);
}
