// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

/* 32-bit table */
// RV32-LABEL: @test_pslideupx_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[RD_COERCE:%.*]], i32 [[RS1_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int8x4_t   test_pslideupx_i8x4(int8x4_t rd, int8x4_t rs1, unsigned rs2)        { return __riscv_pslideupx_i8x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[RD_COERCE:%.*]], i32 [[RS1_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint8x4_t  test_pslideupx_u8x4(uint8x4_t rd, uint8x4_t rs1, unsigned rs2)      { return __riscv_pslideupx_u8x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[RD_COERCE:%.*]], i32 [[RS1_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int16x2_t  test_pslideupx_i16x2(int16x2_t rd, int16x2_t rs1, unsigned rs2)     { return __riscv_pslideupx_i16x2(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshl.i32(i32 [[RD_COERCE:%.*]], i32 [[RS1_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint16x2_t test_pslideupx_u16x2(uint16x2_t rd, uint16x2_t rs1, unsigned rs2)   { return __riscv_pslideupx_u16x2(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshr.i32(i32 [[RS1_COERCE:%.*]], i32 [[RD_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int8x4_t   test_pslidedownx_i8x4(int8x4_t rd, int8x4_t rs1, unsigned rs2)        { return __riscv_pslidedownx_i8x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshr.i32(i32 [[RS1_COERCE:%.*]], i32 [[RD_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint8x4_t  test_pslidedownx_u8x4(uint8x4_t rd, uint8x4_t rs1, unsigned rs2)      { return __riscv_pslidedownx_u8x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshr.i32(i32 [[RS1_COERCE:%.*]], i32 [[RD_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int16x2_t  test_pslidedownx_i16x2(int16x2_t rd, int16x2_t rs1, unsigned rs2)     { return __riscv_pslidedownx_i16x2(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.fshr.i32(i32 [[RS1_COERCE:%.*]], i32 [[RD_COERCE:%.*]], i32 [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint16x2_t test_pslidedownx_u16x2(uint16x2_t rd, uint16x2_t rs1, unsigned rs2)   { return __riscv_pslidedownx_u16x2(rd, rs1, rs2); }

/* 64-bit table */
// RV32-LABEL: @test_pslideupx_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshl.i64(i64 [[RD_COERCE:%.*]], i64 [[RS1_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int8x8_t   test_pslideupx_i8x8(int8x8_t rd, int8x8_t rs1, unsigned rs2)        { return __riscv_pslideupx_i8x8(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_u8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshl.i64(i64 [[RD_COERCE:%.*]], i64 [[RS1_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint8x8_t  test_pslideupx_u8x8(uint8x8_t rd, uint8x8_t rs1, unsigned rs2)      { return __riscv_pslideupx_u8x8(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshl.i64(i64 [[RD_COERCE:%.*]], i64 [[RS1_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t  test_pslideupx_i16x4(int16x4_t rd, int16x4_t rs1, unsigned rs2)     { return __riscv_pslideupx_i16x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshl.i64(i64 [[RD_COERCE:%.*]], i64 [[RS1_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pslideupx_u16x4(uint16x4_t rd, uint16x4_t rs1, unsigned rs2)   { return __riscv_pslideupx_u16x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 5
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshl.i64(i64 [[RD_COERCE:%.*]], i64 [[RS1_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t  test_pslideupx_i32x2(int32x2_t rd, int32x2_t rs1, unsigned rs2)     { return __riscv_pslideupx_i32x2(rd, rs1, rs2); }
// RV32-LABEL: @test_pslideupx_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 5
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshl.i64(i64 [[RD_COERCE:%.*]], i64 [[RS1_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pslideupx_u32x2(uint32x2_t rd, uint32x2_t rs1, unsigned rs2)   { return __riscv_pslideupx_u32x2(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshr.i64(i64 [[RS1_COERCE:%.*]], i64 [[RD_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int8x8_t   test_pslidedownx_i8x8(int8x8_t rd, int8x8_t rs1, unsigned rs2)        { return __riscv_pslidedownx_i8x8(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_u8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 3
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshr.i64(i64 [[RS1_COERCE:%.*]], i64 [[RD_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint8x8_t  test_pslidedownx_u8x8(uint8x8_t rd, uint8x8_t rs1, unsigned rs2)      { return __riscv_pslidedownx_u8x8(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshr.i64(i64 [[RS1_COERCE:%.*]], i64 [[RD_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t  test_pslidedownx_i16x4(int16x4_t rd, int16x4_t rs1, unsigned rs2)     { return __riscv_pslidedownx_i16x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 4
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshr.i64(i64 [[RS1_COERCE:%.*]], i64 [[RD_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pslidedownx_u16x4(uint16x4_t rd, uint16x4_t rs1, unsigned rs2)   { return __riscv_pslidedownx_u16x4(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 5
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshr.i64(i64 [[RS1_COERCE:%.*]], i64 [[RD_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t  test_pslidedownx_i32x2(int32x2_t rd, int32x2_t rs1, unsigned rs2)     { return __riscv_pslidedownx_i32x2(rd, rs1, rs2); }
// RV32-LABEL: @test_pslidedownx_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = shl i32 [[RS2:%.*]], 5
// RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.fshr.i64(i64 [[RS1_COERCE:%.*]], i64 [[RD_COERCE:%.*]], i64 [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pslidedownx_u32x2(uint32x2_t rd, uint32x2_t rs1, unsigned rs2)   { return __riscv_pslidedownx_u32x2(rd, rs1, rs2); }
