// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// 32-bit-input forms (also available on RV64 via widening).
// RV64-LABEL: @test_pmul_b00_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT12_I:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[VECINIT24_I:%.*]] = shufflevector <8 x i8> [[TMP3]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[TMP4:%.*]] = call <4 x i16> @llvm.riscv.pmul.b00.v4i16.v8i8(<8 x i8> [[VECINIT12_I]], <8 x i8> [[VECINIT24_I]])
// RV64-NEXT:    [[VECINIT28_I_BC:%.*]] = bitcast <4 x i16> [[TMP4]] to <2 x i32>
// RV64-NEXT:    [[VECINIT28_I_EXTRACT:%.*]] = extractelement <2 x i32> [[VECINIT28_I_BC]], i64 0
// RV64-NEXT:    ret i32 [[VECINIT28_I_EXTRACT]]
//
int16x2_t test_pmul_b00_i16x2(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmul_b00_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulu_b00_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT12_I:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[VECINIT24_I:%.*]] = shufflevector <8 x i8> [[TMP3]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[TMP4:%.*]] = call <4 x i16> @llvm.riscv.pmulu.b00.v4i16.v8i8(<8 x i8> [[VECINIT12_I]], <8 x i8> [[VECINIT24_I]])
// RV64-NEXT:    [[VECINIT28_I_BC:%.*]] = bitcast <4 x i16> [[TMP4]] to <2 x i32>
// RV64-NEXT:    [[VECINIT28_I_EXTRACT:%.*]] = extractelement <2 x i32> [[VECINIT28_I_BC]], i64 0
// RV64-NEXT:    ret i32 [[VECINIT28_I_EXTRACT]]
//
uint16x2_t test_pmulu_b00_u16x2(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmulu_b00_u16x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulsu_b00_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT12_I:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[VECINIT24_I:%.*]] = shufflevector <8 x i8> [[TMP3]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[TMP4:%.*]] = call <4 x i16> @llvm.riscv.pmulsu.b00.v4i16.v8i8(<8 x i8> [[VECINIT12_I]], <8 x i8> [[VECINIT24_I]])
// RV64-NEXT:    [[VECINIT28_I_BC:%.*]] = bitcast <4 x i16> [[TMP4]] to <2 x i32>
// RV64-NEXT:    [[VECINIT28_I_EXTRACT:%.*]] = extractelement <2 x i32> [[VECINIT28_I_BC]], i64 0
// RV64-NEXT:    ret i32 [[VECINIT28_I_EXTRACT]]
//
int16x2_t test_pmulsu_b00_i16x2(int8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmulsu_b00_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_mul_h00_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT6_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT12_I:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP4:%.*]] = call <2 x i32> @llvm.riscv.pmul.h00.v2i32.v4i16(<4 x i16> [[VECINIT6_I]], <4 x i16> [[VECINIT12_I]])
// RV64-NEXT:    [[VECEXT13_I:%.*]] = extractelement <2 x i32> [[TMP4]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT13_I]]
//
int32_t test_mul_h00_i32(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mul_h00_i32(rs1, rs2);
}
// RV64-LABEL: @test_mulu_h00_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT6_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT12_I:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP4:%.*]] = call <2 x i32> @llvm.riscv.pmulu.h00.v2i32.v4i16(<4 x i16> [[VECINIT6_I]], <4 x i16> [[VECINIT12_I]])
// RV64-NEXT:    [[VECEXT13_I:%.*]] = extractelement <2 x i32> [[TMP4]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT13_I]]
//
uint32_t test_mulu_h00_u32(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_mulu_h00_u32(rs1, rs2);
}
// RV64-LABEL: @test_mulsu_h00_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT6_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT12_I:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP4:%.*]] = call <2 x i32> @llvm.riscv.pmulsu.h00.v2i32.v4i16(<4 x i16> [[VECINIT6_I]], <4 x i16> [[VECINIT12_I]])
// RV64-NEXT:    [[VECEXT13_I:%.*]] = extractelement <2 x i32> [[TMP4]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT13_I]]
//
int32_t test_mulsu_h00_i32(int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_mulsu_h00_i32(rs1, rs2);
}

// 64-bit-input byte family.
// RV64-LABEL: @test_pmul_b00_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmul.b00.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmul_b00_i16x4(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmul_b00_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmul_b01_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmul.b01.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmul_b01_i16x4(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmul_b01_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmul_b11_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmul.b11.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmul_b11_i16x4(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pmul_b11_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulu_b00_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulu.b00.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmulu_b00_u16x4(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmulu_b00_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulu_b01_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulu.b01.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmulu_b01_u16x4(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmulu_b01_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulu_b11_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulu.b11.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pmulu_b11_u16x4(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmulu_b11_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulsu_b00_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulsu.b00.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmulsu_b00_i16x4(int8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmulsu_b00_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulsu_b11_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulsu.b11.v4i16.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmulsu_b11_i16x4(int8x8_t rs1, uint8x8_t rs2) {
  return __riscv_pmulsu_b11_i16x4(rs1, rs2);
}

// 64-bit-input halfword family.
// RV64-LABEL: @test_pmul_h00_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmul.h00.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmul_h00_i32x2(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmul_h00_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmul_h01_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmul.h01.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmul_h01_i32x2(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmul_h01_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmul_h11_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmul.h11.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmul_h11_i32x2(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmul_h11_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulu_h00_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulu.h00.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmulu_h00_u32x2(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulu_h00_u32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulu_h01_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulu.h01.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmulu_h01_u32x2(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulu_h01_u32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulu_h11_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulu.h11.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_pmulu_h11_u32x2(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulu_h11_u32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulsu_h00_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulsu.h00.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmulsu_h00_i32x2(int16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulsu_h00_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulsu_h11_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulsu.h11.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmulsu_h11_i32x2(int16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulsu_h11_i32x2(rs1, rs2);
}

// 64-bit-input word family (scalar i64).
// RV64-LABEL: @test_mul_w00_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmul.w00.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mul_w00_i64(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mul_w00_i64(rs1, rs2);
}
// RV64-LABEL: @test_mul_w01_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmul.w01.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mul_w01_i64(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mul_w01_i64(rs1, rs2);
}
// RV64-LABEL: @test_mul_w11_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmul.w11.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mul_w11_i64(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mul_w11_i64(rs1, rs2);
}
// RV64-LABEL: @test_mulu_w00_u64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmulu.w00.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint64_t test_mulu_w00_u64(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_mulu_w00_u64(rs1, rs2);
}
// RV64-LABEL: @test_mulu_w01_u64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmulu.w01.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint64_t test_mulu_w01_u64(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_mulu_w01_u64(rs1, rs2);
}
// RV64-LABEL: @test_mulu_w11_u64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmulu.w11.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint64_t test_mulu_w11_u64(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_mulu_w11_u64(rs1, rs2);
}
// RV64-LABEL: @test_mulsu_w00_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmulsu.w00.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mulsu_w00_i64(int32x2_t rs1, uint32x2_t rs2) {
  return __riscv_mulsu_w00_i64(rs1, rs2);
}
// RV64-LABEL: @test_mulsu_w11_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmulsu.w11.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mulsu_w11_i64(int32x2_t rs1, uint32x2_t rs2) {
  return __riscv_mulsu_w11_i64(rs1, rs2);
}
