// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// pm4add byte (64-bit input -> v2i32)

// RV64-LABEL: define dso_local i64 @test_pm4add_i8x8(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0:[0-9]+]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pm4add.v2i32.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pm4add_i8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pm4add_i8x8(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pm4adda_i8x8(
// RV64-SAME: i64 noundef [[RD_COERCE:%.*]], i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE]] to <8 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pm4adda.v2i32.v8i8(<2 x i32> [[TMP0]], <8 x i8> [[TMP1]], <8 x i8> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pm4adda_i8x8(int32x2_t rd, int8x8_t rs1, int8x8_t rs2) {
  return __riscv_pm4adda_i8x8(rd, rs1, rs2);
}

// pm4add halfword (64-bit input -> i64 scalar)

// RV64-LABEL: define dso_local i64 @test_pm4add_i16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm4add.i64.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm4add_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pm4add_i16x4(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pm4adda_i16x4(
// RV64-SAME: i64 noundef [[RD:%.*]], i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm4adda.i64.v4i16(i64 [[RD]], <4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm4adda_i16x4(int64_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pm4adda_i16x4(rd, rs1, rs2);
}

// pm2add halfword (64-bit input -> v2i32)

// RV64-LABEL: define dso_local i64 @test_pm2add_i16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pm2add.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pm2add_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pm2add_i16x4(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pm2adda_x_i16x4(
// RV64-SAME: i64 noundef [[RD_COERCE:%.*]], i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pm2adda.x.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pm2adda_x_i16x4(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pm2adda_x_i16x4(rd, rs1, rs2);
}

// pm2add word (64-bit input -> i64 scalar)

// RV64-LABEL: define dso_local i64 @test_pm2add_i32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2add.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2add_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pm2add_i32x2(rs1, rs2);
}

// RV64-LABEL: define dso_local i64 @test_pm2sub_x_i32x2(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2sub.x.i64.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2sub_x_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pm2sub_x_i32x2(rs1, rs2);
}

// Q-format halfword

// RV64-LABEL: define dso_local i64 @test_pmqr2adda_i16x4(
// RV64-SAME: i64 noundef [[RD_COERCE:%.*]], i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmqr2adda.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmqr2adda_i16x4(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmqr2adda_i16x4(rd, rs1, rs2);
}

// Saturating halfword (no accumulator)

// RV64-LABEL: define dso_local i64 @test_pm2sadd_i16x4(
// RV64-SAME: i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pm2sadd.v2i32.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pm2sadd_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pm2sadd_i16x4(rs1, rs2);
}

// Multiply-subtract halfword

// RV64-LABEL: define dso_local i64 @test_pm2suba_i16x4(
// RV64-SAME: i64 noundef [[RD_COERCE:%.*]], i64 noundef [[RS1_COERCE:%.*]], i64 noundef [[RS2_COERCE:%.*]]) #[[ATTR0]] {
// RV64-NEXT:  [[ENTRY:.*:]]
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pm2suba.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pm2suba_i16x4(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pm2suba_i16x4(rd, rs1, rs2);
}
