// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_mqacc_h00_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmqacc.h00.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mqacc_h00_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqacc_h00_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mqacc_h01_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmqacc.h01.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mqacc_h01_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqacc_h01_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mqacc_h11_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmqacc.h11.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mqacc_h11_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqacc_h11_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mqracc_h00_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmqracc.h00.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mqracc_h00_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqracc_h00_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mqracc_h01_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmqracc.h01.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mqracc_h01_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqracc_h01_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mqracc_h11_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmqracc.h11.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mqracc_h11_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqracc_h11_i32(rd, rs1, rs2);
}
