// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pzip_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pzip.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int8x8_t test_pzip_i8x8(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pzip_i8x8(rs1, rs2);
}
// RV32-LABEL: @test_pzip_u8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pzip.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint8x8_t test_pzip_u8x8(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pzip_u8x8(rs1, rs2);
}
// RV32-LABEL: @test_pzip_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pzip.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pzip_i16x4(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pzip_i16x4(rs1, rs2);
}
// RV32-LABEL: @test_pzip_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pzip.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pzip_u16x4(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pzip_u16x4(rs1, rs2);
}
