// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_pget_i8x8_i8x4_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc i64 [[V_COERCE:%.*]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
int8x4_t   test_pget_i8x8_i8x4_lo(int8x8_t v)   { return __riscv_pget_i8x8_i8x4(v, 0); }
// RV64-LABEL: @test_pget_i8x8_i8x4_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 32
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc nuw i64 [[EXTELT_OFFSET]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
int8x4_t   test_pget_i8x8_i8x4_hi(int8x8_t v)   { return __riscv_pget_i8x8_i8x4(v, 1); }
// RV64-LABEL: @test_pget_u8x8_u8x4_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc i64 [[V_COERCE:%.*]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
uint8x4_t  test_pget_u8x8_u8x4_lo(uint8x8_t v)  { return __riscv_pget_u8x8_u8x4(v, 0); }
// RV64-LABEL: @test_pget_u8x8_u8x4_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 32
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc nuw i64 [[EXTELT_OFFSET]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
uint8x4_t  test_pget_u8x8_u8x4_hi(uint8x8_t v)  { return __riscv_pget_u8x8_u8x4(v, 1); }
// RV64-LABEL: @test_pget_i16x4_i16x2_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc i64 [[V_COERCE:%.*]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
int16x2_t  test_pget_i16x4_i16x2_lo(int16x4_t v)  { return __riscv_pget_i16x4_i16x2(v, 0); }
// RV64-LABEL: @test_pget_i16x4_i16x2_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 32
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc nuw i64 [[EXTELT_OFFSET]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
int16x2_t  test_pget_i16x4_i16x2_hi(int16x4_t v)  { return __riscv_pget_i16x4_i16x2(v, 1); }
// RV64-LABEL: @test_pget_u16x4_u16x2_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc i64 [[V_COERCE:%.*]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
uint16x2_t test_pget_u16x4_u16x2_lo(uint16x4_t v) { return __riscv_pget_u16x4_u16x2(v, 0); }
// RV64-LABEL: @test_pget_u16x4_u16x2_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 32
// RV64-NEXT:    [[DOTEXTRACT:%.*]] = trunc nuw i64 [[EXTELT_OFFSET]] to i32
// RV64-NEXT:    ret i32 [[DOTEXTRACT]]
//
uint16x2_t test_pget_u16x4_u16x2_hi(uint16x4_t v) { return __riscv_pget_u16x4_u16x2(v, 1); }

// RV64-LABEL: @test_pset_i8x4_i8x8_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], -4294967296
// RV64-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV64-NEXT:    ret i64 [[TMP2]]
//
int8x8_t   test_pset_i8x4_i8x8_lo(int8x8_t v, int8x4_t s)   { return __riscv_pset_i8x4_i8x8(v, s, 0); }
// RV64-LABEL: @test_pset_i8x4_i8x8_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], 4294967295
// RV64-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 32
// RV64-NEXT:    [[TMP3:%.*]] = or disjoint i64 [[TMP1]], [[TMP2]]
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t   test_pset_i8x4_i8x8_hi(int8x8_t v, int8x4_t s)   { return __riscv_pset_i8x4_i8x8(v, s, 1); }
// RV64-LABEL: @test_pset_u8x4_u8x8_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], -4294967296
// RV64-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint8x8_t  test_pset_u8x4_u8x8_lo(uint8x8_t v, uint8x4_t s) { return __riscv_pset_u8x4_u8x8(v, s, 0); }
// RV64-LABEL: @test_pset_u8x4_u8x8_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], 4294967295
// RV64-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 32
// RV64-NEXT:    [[TMP3:%.*]] = or disjoint i64 [[TMP1]], [[TMP2]]
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pset_u8x4_u8x8_hi(uint8x8_t v, uint8x4_t s) { return __riscv_pset_u8x4_u8x8(v, s, 1); }
// RV64-LABEL: @test_pset_i16x2_i16x4_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], -4294967296
// RV64-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t  test_pset_i16x2_i16x4_lo(int16x4_t v, int16x2_t s)  { return __riscv_pset_i16x2_i16x4(v, s, 0); }
// RV64-LABEL: @test_pset_i16x2_i16x4_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], 4294967295
// RV64-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 32
// RV64-NEXT:    [[TMP3:%.*]] = or disjoint i64 [[TMP1]], [[TMP2]]
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t  test_pset_i16x2_i16x4_hi(int16x4_t v, int16x2_t s)  { return __riscv_pset_i16x2_i16x4(v, s, 1); }
// RV64-LABEL: @test_pset_u16x2_u16x4_lo(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], -4294967296
// RV64-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP1]], [[TMP0]]
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pset_u16x2_u16x4_lo(uint16x4_t v, uint16x2_t s) { return __riscv_pset_u16x2_u16x4(v, s, 0); }
// RV64-LABEL: @test_pset_u16x2_u16x4_hi(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[S_COERCE:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = and i64 [[V_COERCE:%.*]], 4294967295
// RV64-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 32
// RV64-NEXT:    [[TMP3:%.*]] = or disjoint i64 [[TMP1]], [[TMP2]]
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pset_u16x2_u16x4_hi(uint16x4_t v, uint16x2_t s) { return __riscv_pset_u16x2_u16x4(v, s, 1); }
