// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=mem2reg,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_ssha_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ssha.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_ssha_i32(int32_t a, int b)   { return __riscv_ssha_i32(a, b); }
// RV32-LABEL: @test_sshar_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sshar.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_sshar_i32(int32_t a, int b)  { return __riscv_sshar_i32(a, b); }
// RV32-LABEL: @test_sshl_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sshl.u32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_sshl_u32(int32_t a, int b)   { return __riscv_sshl_u32(a, b); }
// RV32-LABEL: @test_sshlr_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sshlr.u32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_sshlr_u32(int32_t a, int b)  { return __riscv_sshlr_u32(a, b); }
