// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pmul_b00_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmul.b00.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmul_b00_i16x2(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmul_b00_i16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmul_b01_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmul.b01.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmul_b01_i16x2(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmul_b01_i16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmul_b11_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmul.b11.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmul_b11_i16x2(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pmul_b11_i16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulu_b00_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulu.b00.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmulu_b00_u16x2(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmulu_b00_u16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulu_b01_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulu.b01.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmulu_b01_u16x2(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmulu_b01_u16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulu_b11_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulu.b11.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmulu_b11_u16x2(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmulu_b11_u16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulsu_b00_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulsu.b00.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmulsu_b00_i16x2(int8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmulsu_b00_i16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulsu_b11_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulsu.b11.v2i16.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmulsu_b11_i16x2(int8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pmulsu_b11_i16x2(rs1, rs2);
}

// RV32-LABEL: @test_mul_h00_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmul.h00.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mul_h00_i32(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mul_h00_i32(rs1, rs2);
}
// RV32-LABEL: @test_mul_h01_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmul.h01.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mul_h01_i32(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mul_h01_i32(rs1, rs2);
}
// RV32-LABEL: @test_mul_h11_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmul.h11.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mul_h11_i32(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mul_h11_i32(rs1, rs2);
}
// RV32-LABEL: @test_mulu_h00_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmulu.h00.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint32_t test_mulu_h00_u32(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_mulu_h00_u32(rs1, rs2);
}
// RV32-LABEL: @test_mulu_h01_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmulu.h01.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint32_t test_mulu_h01_u32(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_mulu_h01_u32(rs1, rs2);
}
// RV32-LABEL: @test_mulu_h11_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmulu.h11.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint32_t test_mulu_h11_u32(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_mulu_h11_u32(rs1, rs2);
}
// RV32-LABEL: @test_mulsu_h00_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmulsu.h00.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mulsu_h00_i32(int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_mulsu_h00_i32(rs1, rs2);
}
// RV32-LABEL: @test_mulsu_h11_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmulsu.h11.i32.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_mulsu_h11_i32(int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_mulsu_h11_i32(rs1, rs2);
}
