// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pwmul_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwmul.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwmul_i16x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pwmul_i16x4(rs1, rs2);
}
// RV32-LABEL: @test_pwmul_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwmul.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwmul_i32x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pwmul_i32x2(rs1, rs2);
}
// RV32-LABEL: @test_pwmulu_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwmulu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwmulu_u16x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pwmulu_u16x4(rs1, rs2);
}
// RV32-LABEL: @test_pwmulu_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwmulu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwmulu_u32x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pwmulu_u32x2(rs1, rs2);
}
// RV32-LABEL: @test_pwmulsu_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwmulsu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwmulsu_i16x4(int8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pwmulsu_i16x4(rs1, rs2);
}
// RV32-LABEL: @test_pwmulsu_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwmulsu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwmulsu_i32x2(int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pwmulsu_i32x2(rs1, rs2);
}
