// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_psh1add_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.psh1add.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_psh1add_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_psh1add_i16x2(rs1, rs2);
}

// RV64-LABEL: @test_psh1add_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.psh1add.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_psh1add_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_psh1add_u16x2(rs1, rs2);
}

// RV64-LABEL: @test_pssh1sadd_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pssh1sadd.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pssh1sadd_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pssh1sadd_i16x2(rs1, rs2);
}

// RV64-LABEL: @test_psh1add_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.psh1add.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_psh1add_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_psh1add_i16x4(rs1, rs2);
}

// RV64-LABEL: @test_psh1add_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.psh1add.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_psh1add_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_psh1add_u16x4(rs1, rs2);
}

// RV64-LABEL: @test_psh1add_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.psh1add.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_psh1add_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_psh1add_i32x2(rs1, rs2);
}

// RV64-LABEL: @test_psh1add_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.psh1add.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_psh1add_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_psh1add_u32x2(rs1, rs2);
}

// RV64-LABEL: @test_pssh1sadd_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pssh1sadd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pssh1sadd_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pssh1sadd_i16x4(rs1, rs2);
}

// RV64-LABEL: @test_pssh1sadd_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pssh1sadd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pssh1sadd_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pssh1sadd_i32x2(rs1, rs2);
}
