// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_sadd_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[ELT_SAT_I:%.*]] = call i32 @llvm.sadd.sat.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV64-NEXT:    ret i32 [[ELT_SAT_I]]
//
int32_t  test_sadd_i32(int32_t a, int32_t b)    { return __riscv_sadd_i32(a, b); }
// RV64-LABEL: @test_saddu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[ELT_SAT_I:%.*]] = call i32 @llvm.uadd.sat.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV64-NEXT:    ret i32 [[ELT_SAT_I]]
//
uint32_t test_saddu_u32(uint32_t a, uint32_t b) { return __riscv_saddu_u32(a, b); }
// RV64-LABEL: @test_ssub_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[ELT_SAT_I:%.*]] = call i32 @llvm.ssub.sat.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV64-NEXT:    ret i32 [[ELT_SAT_I]]
//
int32_t  test_ssub_i32(int32_t a, int32_t b)    { return __riscv_ssub_i32(a, b); }
// RV64-LABEL: @test_ssubu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[ELT_SAT_I:%.*]] = call i32 @llvm.usub.sat.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV64-NEXT:    ret i32 [[ELT_SAT_I]]
//
uint32_t test_ssubu_u32(uint32_t a, uint32_t b) { return __riscv_ssubu_u32(a, b); }
// RV64-LABEL: @test_slx_32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.fshl.i32(i32 [[A:%.*]], i32 [[B:%.*]], i32 [[S:%.*]])
// RV64-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_slx_32(uint32_t a, uint32_t b, unsigned s) { return __riscv_slx_32(a, b, s); }
// RV64-LABEL: @test_srx_32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.fshr.i32(i32 [[B:%.*]], i32 [[A:%.*]], i32 [[S:%.*]])
// RV64-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_srx_32(uint32_t a, uint32_t b, unsigned s) { return __riscv_srx_32(a, b, s); }

/* RV64-only funnel shifts */
// RV64-LABEL: @test_slx_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[CONV_I:%.*]] = zext i32 [[S:%.*]] to i64
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.fshl.i64(i64 [[A:%.*]], i64 [[B:%.*]], i64 [[CONV_I]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_slx_64(uint64_t a, uint64_t b, unsigned s) { return __riscv_slx_64(a, b, s); }
// RV64-LABEL: @test_srx_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[CONV_I:%.*]] = zext i32 [[S:%.*]] to i64
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.fshr.i64(i64 [[B:%.*]], i64 [[A:%.*]], i64 [[CONV_I]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_srx_64(uint64_t a, uint64_t b, unsigned s) { return __riscv_srx_64(a, b, s); }
