// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

/* Packed <-> Scalar (32-bit) */
// RV32-LABEL: @t_u8x4_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
uint32_t   t_u8x4_u32 (uint8x4_t  x) { return __riscv_preinterpret_u8x4_u32 (x); }
// RV32-LABEL: @t_u16x2_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
uint32_t   t_u16x2_u32(uint16x2_t x) { return __riscv_preinterpret_u16x2_u32(x); }
// RV32-LABEL: @t_i8x4_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
uint32_t   t_i8x4_u32 (int8x4_t   x) { return __riscv_preinterpret_i8x4_u32 (x); }
// RV32-LABEL: @t_i16x2_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
uint32_t   t_i16x2_u32(int16x2_t  x) { return __riscv_preinterpret_i16x2_u32(x); }
// RV32-LABEL: @t_u8x4_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
int32_t    t_u8x4_i32 (uint8x4_t  x) { return __riscv_preinterpret_u8x4_i32 (x); }
// RV32-LABEL: @t_u16x2_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
int32_t    t_u16x2_i32(uint16x2_t x) { return __riscv_preinterpret_u16x2_i32(x); }
// RV32-LABEL: @t_i8x4_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
int32_t    t_i8x4_i32 (int8x4_t   x) { return __riscv_preinterpret_i8x4_i32 (x); }
// RV32-LABEL: @t_i16x2_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
int32_t    t_i16x2_i32(int16x2_t  x) { return __riscv_preinterpret_i16x2_i32(x); }
// RV32-LABEL: @t_u32_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
uint8x4_t  t_u32_u8x4 (uint32_t   x) { return __riscv_preinterpret_u32_u8x4 (x); }
// RV32-LABEL: @t_u32_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
uint16x2_t t_u32_u16x2(uint32_t   x) { return __riscv_preinterpret_u32_u16x2(x); }
// RV32-LABEL: @t_u32_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
int8x4_t   t_u32_i8x4 (uint32_t   x) { return __riscv_preinterpret_u32_i8x4 (x); }
// RV32-LABEL: @t_u32_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
int16x2_t  t_u32_i16x2(uint32_t   x) { return __riscv_preinterpret_u32_i16x2(x); }
// RV32-LABEL: @t_i32_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
uint8x4_t  t_i32_u8x4 (int32_t    x) { return __riscv_preinterpret_i32_u8x4 (x); }
// RV32-LABEL: @t_i32_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
uint16x2_t t_i32_u16x2(int32_t    x) { return __riscv_preinterpret_i32_u16x2(x); }
// RV32-LABEL: @t_i32_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
int8x4_t   t_i32_i8x4 (int32_t    x) { return __riscv_preinterpret_i32_i8x4 (x); }
// RV32-LABEL: @t_i32_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X:%.*]]
//
int16x2_t  t_i32_i16x2(int32_t    x) { return __riscv_preinterpret_i32_i16x2(x); }

/* Packed <-> Scalar (64-bit) — selected representative pairs */
// RV32-LABEL: @t_u8x8_u64(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i64 [[X_COERCE:%.*]]
//
uint64_t   t_u8x8_u64 (uint8x8_t  x) { return __riscv_preinterpret_u8x8_u64 (x); }
// RV32-LABEL: @t_i32x2_u64(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i64 [[X_COERCE:%.*]]
//
uint64_t   t_i32x2_u64(int32x2_t  x) { return __riscv_preinterpret_i32x2_u64(x); }
// RV32-LABEL: @t_u64_i8x8(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i64 [[X:%.*]]
//
int8x8_t   t_u64_i8x8 (uint64_t   x) { return __riscv_preinterpret_u64_i8x8 (x); }
// RV32-LABEL: @t_i64_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i64 [[X:%.*]]
//
int32x2_t  t_i64_i32x2(int64_t    x) { return __riscv_preinterpret_i64_i32x2(x); }

/* Packed <-> Packed (32-bit) — selected representative pairs */
// RV32-LABEL: @t_i8x4_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
uint8x4_t  t_i8x4_u8x4 (int8x4_t   x) { return __riscv_preinterpret_i8x4_u8x4 (x); }
// RV32-LABEL: @t_u8x4_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i32 [[X_COERCE:%.*]]
//
int16x2_t  t_u8x4_i16x2(uint8x4_t  x) { return __riscv_preinterpret_u8x4_i16x2(x); }

/* Packed <-> Packed (64-bit) — selected representative pairs */
// RV32-LABEL: @t_u8x8_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i64 [[X_COERCE:%.*]]
//
int32x2_t  t_u8x8_i32x2(uint8x8_t  x) { return __riscv_preinterpret_u8x8_i32x2(x); }
// RV32-LABEL: @t_i32x2_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    ret i64 [[X_COERCE:%.*]]
//
uint16x4_t t_i32x2_u16x4(int32x2_t x) { return __riscv_preinterpret_i32x2_u16x4(x); }
