// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_ppaire_i8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppaire.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int8x4_t test_ppaire_i8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_ppaire_i8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_u8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppaire.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t test_ppaire_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_ppaire_u8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_i8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppaireo.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int8x4_t test_ppaireo_i8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_ppaireo_i8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_u8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppaireo.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t test_ppaireo_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_ppaireo_u8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_i8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppairoe.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int8x4_t test_ppairoe_i8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_ppairoe_i8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_u8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppairoe.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t test_ppairoe_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_ppairoe_u8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_i8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppairo.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int8x4_t test_ppairo_i8x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_ppairo_i8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_u8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i8> @llvm.riscv.ppairo.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint8x4_t test_ppairo_u8x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_ppairo_u8x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppaire.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_ppaire_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_ppaire_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppaire.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_ppaire_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_ppaire_u16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppaireo.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_ppaireo_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_ppaireo_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppaireo.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_ppaireo_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_ppaireo_u16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppairoe.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_ppairoe_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_ppairoe_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppairoe.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_ppairoe_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_ppairoe_u16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppairo.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_ppairo_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_ppairo_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.ppairo.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_ppairo_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_ppairo_u16x2(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppaire.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_ppaire_i8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_ppaire_i8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppaire.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_ppaire_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_ppaire_u8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppaireo.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_ppaireo_i8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_ppaireo_i8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppaireo.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_ppaireo_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_ppaireo_u8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppairoe.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_ppairoe_i8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_ppairoe_i8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppairoe.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_ppairoe_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_ppairoe_u8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppairo.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_ppairo_i8x8(int8x8_t rs1, int8x8_t rs2) {
  return __riscv_ppairo_i8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.ppairo.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_ppairo_u8x8(uint8x8_t rs1, uint8x8_t rs2) {
  return __riscv_ppairo_u8x8(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppaire.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_ppaire_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_ppaire_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppaire.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_ppaire_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_ppaire_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppaireo.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_ppaireo_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_ppaireo_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppaireo.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_ppaireo_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_ppaireo_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppairoe.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_ppairoe_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_ppairoe_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppairoe.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_ppairoe_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_ppairoe_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppairo.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_ppairo_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_ppairo_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.ppairo.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_ppairo_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_ppairo_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppaire.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_ppaire_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_ppaire_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_ppaire_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppaire.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_ppaire_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_ppaire_u32x2(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppaireo.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_ppaireo_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_ppaireo_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_ppaireo_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppaireo.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_ppaireo_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_ppaireo_u32x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppairoe.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_ppairoe_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_ppairoe_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairoe_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppairoe.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_ppairoe_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_ppairoe_u32x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppairo.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_ppairo_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_ppairo_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_ppairo_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.ppairo.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_ppairo_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_ppairo_u32x2(rs1, rs2);
}
