// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// Cross-XLEN forms (mapped to .h.b0 / pmulh.w.h0 with widening on RV64).
// RV64-LABEL: @test_pmulh_b0_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT6_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT18_I:%.*]] = shufflevector <8 x i8> [[TMP3]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[TMP4:%.*]] = call <4 x i16> @llvm.riscv.pmulh.b0.v4i16.v8i8(<4 x i16> [[VECINIT6_I]], <8 x i8> [[VECINIT18_I]])
// RV64-NEXT:    [[VECINIT22_I_BC:%.*]] = bitcast <4 x i16> [[TMP4]] to <2 x i32>
// RV64-NEXT:    [[VECINIT22_I_EXTRACT:%.*]] = extractelement <2 x i32> [[VECINIT22_I_BC]], i64 0
// RV64-NEXT:    ret i32 [[VECINIT22_I_EXTRACT]]
//
int16x2_t test_pmulh_b0_i16x2(int16x2_t rs1, int8x4_t rs2) {
  return __riscv_pmulh_b0_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulhsu_b1_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT6_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT18_I:%.*]] = shufflevector <8 x i8> [[TMP3]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[TMP4:%.*]] = call <4 x i16> @llvm.riscv.pmulhsu.b1.v4i16.v8i8(<4 x i16> [[VECINIT6_I]], <8 x i8> [[VECINIT18_I]])
// RV64-NEXT:    [[VECINIT22_I_BC:%.*]] = bitcast <4 x i16> [[TMP4]] to <2 x i32>
// RV64-NEXT:    [[VECINIT22_I_EXTRACT:%.*]] = extractelement <2 x i32> [[VECINIT22_I_BC]], i64 0
// RV64-NEXT:    ret i32 [[VECINIT22_I_EXTRACT]]
//
int16x2_t test_pmulhsu_b1_i16x2(int16x2_t rs1, uint8x4_t rs2) {
  return __riscv_pmulhsu_b1_i16x2(rs1, rs2);
}
// RV64-LABEL: @test_mulh_h0_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT2_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RS1:%.*]], i64 0
// RV64-NEXT:    [[VECINIT7_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulh.h0.v2i32.v4i16(<2 x i32> [[VECINIT2_I]], <4 x i16> [[VECINIT7_I]])
// RV64-NEXT:    [[VECEXT8_I:%.*]] = extractelement <2 x i32> [[TMP2]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT8_I]]
//
int32_t test_mulh_h0_i32(int32_t rs1, int16x2_t rs2) {
  return __riscv_mulh_h0_i32(rs1, rs2);
}
// RV64-LABEL: @test_mulhsu_h1_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT2_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RS1:%.*]], i64 0
// RV64-NEXT:    [[VECINIT7_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulhsu.h1.v2i32.v4i16(<2 x i32> [[VECINIT2_I]], <4 x i16> [[VECINIT7_I]])
// RV64-NEXT:    [[VECEXT8_I:%.*]] = extractelement <2 x i32> [[TMP2]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT8_I]]
//
int32_t test_mulhsu_h1_i32(int32_t rs1, uint16x2_t rs2) {
  return __riscv_mulhsu_h1_i32(rs1, rs2);
}

// Byte-lane form (RV64 only).
// RV64-LABEL: @test_pmulh_b0_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulh.b0.v4i16.v8i8(<4 x i16> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmulh_b0_i16x4(int16x4_t rs1, int8x8_t rs2) {
  return __riscv_pmulh_b0_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulh_b1_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulh.b1.v4i16.v8i8(<4 x i16> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmulh_b1_i16x4(int16x4_t rs1, int8x8_t rs2) {
  return __riscv_pmulh_b1_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulhsu_b0_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulhsu.b0.v4i16.v8i8(<4 x i16> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmulhsu_b0_i16x4(int16x4_t rs1, uint8x8_t rs2) {
  return __riscv_pmulhsu_b0_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pmulhsu_b1_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pmulhsu.b1.v4i16.v8i8(<4 x i16> [[TMP0]], <8 x i8> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pmulhsu_b1_i16x4(int16x4_t rs1, uint8x8_t rs2) {
  return __riscv_pmulhsu_b1_i16x4(rs1, rs2);
}

// Halfword-lane vector form (RV64 only, pmulh.w.h*).
// RV64-LABEL: @test_pmulh_h0_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulh.h0.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmulh_h0_i32x2(int32x2_t rs1, int16x4_t rs2) {
  return __riscv_pmulh_h0_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulh_h1_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulh.h1.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmulh_h1_i32x2(int32x2_t rs1, int16x4_t rs2) {
  return __riscv_pmulh_h1_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulhsu_h0_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulhsu.h0.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmulhsu_h0_i32x2(int32x2_t rs1, uint16x4_t rs2) {
  return __riscv_pmulhsu_h0_i32x2(rs1, rs2);
}
// RV64-LABEL: @test_pmulhsu_h1_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmulhsu.h1.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <2 x i32> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_pmulhsu_h1_i32x2(int32x2_t rs1, uint16x4_t rs2) {
  return __riscv_pmulhsu_h1_i32x2(rs1, rs2);
}
