// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pm2wadd_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wadd.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wadd_i64(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wadd_i64(rs1, rs2);
}
// RV32-LABEL: @test_pm2wadda_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wadda.v2i16(i64 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wadda_i64(int64_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wadda_i64(rd, rs1, rs2);
}
// RV32-LABEL: @test_pm2wadd_x_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wadd.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wadd_x_i64(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wadd_x_i64(rs1, rs2);
}
// RV32-LABEL: @test_pm2wadda_x_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wadda.x.v2i16(i64 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wadda_x_i64(int64_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wadda_x_i64(rd, rs1, rs2);
}
// RV32-LABEL: @test_pm2waddu_u64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2waddu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint64_t test_pm2waddu_u64(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pm2waddu_u64(rs1, rs2);
}
// RV32-LABEL: @test_pm2waddau_u64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2waddau.v2i16(i64 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint64_t test_pm2waddau_u64(uint64_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pm2waddau_u64(rd, rs1, rs2);
}
// RV32-LABEL: @test_pm2wsub_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wsub.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wsub_i64(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wsub_i64(rs1, rs2);
}
// RV32-LABEL: @test_pm2wsuba_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wsuba.v2i16(i64 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wsuba_i64(int64_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wsuba_i64(rd, rs1, rs2);
}
// RV32-LABEL: @test_pm2wsub_x_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wsub.x.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wsub_x_i64(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wsub_x_i64(rs1, rs2);
}
// RV32-LABEL: @test_pm2wsuba_x_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2wsuba.x.v2i16(i64 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2wsuba_x_i64(int64_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pm2wsuba_x_i64(rd, rs1, rs2);
}
// RV32-LABEL: @test_pm2waddsu_u64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2waddsu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2waddsu_u64(int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pm2waddsu_u64(rs1, rs2);
}
// RV32-LABEL: @test_pm2waddasu_u64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pm2waddasu.v2i16(i64 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int64_t test_pm2waddasu_u64(int64_t rd, int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pm2waddasu_u64(rd, rs1, rs2);
}
