// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pmhacc_b0_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP3:%.*]] = call <2 x i16> @llvm.riscv.pmhacc.b0.v2i16.v4i8(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]], <4 x i8> [[TMP2]])
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
int16x2_t test_pmhacc_b0_i16x2(int16x2_t rd, int16x2_t rs1, int8x4_t rs2) {
  return __riscv_pmhacc_b0_i16x2(rd, rs1, rs2);
}
// RV32-LABEL: @test_pmhacc_b1_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP3:%.*]] = call <2 x i16> @llvm.riscv.pmhacc.b1.v2i16.v4i8(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]], <4 x i8> [[TMP2]])
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
int16x2_t test_pmhacc_b1_i16x2(int16x2_t rd, int16x2_t rs1, int8x4_t rs2) {
  return __riscv_pmhacc_b1_i16x2(rd, rs1, rs2);
}
// RV32-LABEL: @test_pmhaccsu_b0_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP3:%.*]] = call <2 x i16> @llvm.riscv.pmhaccsu.b0.v2i16.v4i8(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]], <4 x i8> [[TMP2]])
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
int16x2_t test_pmhaccsu_b0_i16x2(int16x2_t rd, int16x2_t rs1, uint8x4_t rs2) {
  return __riscv_pmhaccsu_b0_i16x2(rd, rs1, rs2);
}
// RV32-LABEL: @test_pmhaccsu_b1_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP3:%.*]] = call <2 x i16> @llvm.riscv.pmhaccsu.b1.v2i16.v4i8(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]], <4 x i8> [[TMP2]])
// RV32-NEXT:    [[TMP4:%.*]] = bitcast <2 x i16> [[TMP3]] to i32
// RV32-NEXT:    ret i32 [[TMP4]]
//
int16x2_t test_pmhaccsu_b1_i16x2(int16x2_t rd, int16x2_t rs1, uint8x4_t rs2) {
  return __riscv_pmhaccsu_b1_i16x2(rd, rs1, rs2);
}

// RV32-LABEL: @test_mhacc_h0_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmhacc.h0.i32.v2i16(i32 [[RD:%.*]], i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mhacc_h0_i32(int32_t rd, int32_t rs1, int16x2_t rs2) {
  return __riscv_mhacc_h0_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mhacc_h1_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmhacc.h1.i32.v2i16(i32 [[RD:%.*]], i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mhacc_h1_i32(int32_t rd, int32_t rs1, int16x2_t rs2) {
  return __riscv_mhacc_h1_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mhaccsu_h0_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmhaccsu.h0.i32.v2i16(i32 [[RD:%.*]], i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mhaccsu_h0_i32(int32_t rd, int32_t rs1, uint16x2_t rs2) {
  return __riscv_mhaccsu_h0_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_mhaccsu_h1_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmhaccsu.h1.i32.v2i16(i32 [[RD:%.*]], i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mhaccsu_h1_i32(int32_t rd, int32_t rs1, uint16x2_t rs2) {
  return __riscv_mhaccsu_h1_i32(rd, rs1, rs2);
}
