// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_abs_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.abs.i32(i32 [[X:%.*]], i1 true)
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_abs_u32(int32_t x) { return __riscv_abs_u32(x); }
// RV32-LABEL: @test_cls_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[X_LOBIT:%.*]] = ashr i32 [[X:%.*]], 31
// RV32-NEXT:    [[TMP0:%.*]] = xor i32 [[X]], [[X_LOBIT]]
// RV32-NEXT:    [[TMP1:%.*]] = call range(i32 0, 33) i32 @llvm.ctlz.i32(i32 [[TMP0]], i1 false)
// RV32-NEXT:    [[TMP2:%.*]] = add nsw i32 [[TMP1]], -1
// RV32-NEXT:    ret i32 [[TMP2]]
//
unsigned test_cls_32(int32_t x)  { return __riscv_cls_32(x); }
// RV32-LABEL: @test_rev_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.bitreverse.i32(i32 [[X:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_rev_32(uint32_t x) { return __riscv_rev_32(x); }
