// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pncvt_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <4 x i8> @llvm.riscv.pnsrl.v4i8(i64 [[RS1_COERCE:%.*]], i32 0)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
int8x4_t test_pncvt_i8x4(int16x4_t rs1) {
  return __riscv_pncvt_i8x4(rs1);
}
// RV32-LABEL: @test_pncvt_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <4 x i8> @llvm.riscv.pnsrl.v4i8(i64 [[RS1_COERCE:%.*]], i32 0)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint8x4_t test_pncvt_u8x4(uint16x4_t rs1) {
  return __riscv_pncvt_u8x4(rs1);
}
// RV32-LABEL: @test_pncvt_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <2 x i16> @llvm.riscv.pnsrl.v2i16(i64 [[RS1_COERCE:%.*]], i32 0)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
int16x2_t test_pncvt_i16x2(int32x2_t rs1) {
  return __riscv_pncvt_i16x2(rs1);
}
// RV32-LABEL: @test_pncvt_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <2 x i16> @llvm.riscv.pnsrl.v2i16(i64 [[RS1_COERCE:%.*]], i32 0)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint16x2_t test_pncvt_u16x2(uint32x2_t rs1) {
  return __riscv_pncvt_u16x2(rs1);
}
// RV32-LABEL: @test_pncvth_i8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <4 x i8> @llvm.riscv.pnsrl.v4i8(i64 [[RS1_COERCE:%.*]], i32 8)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
int8x4_t test_pncvth_i8x4(int16x4_t rs1) {
  return __riscv_pncvth_i8x4(rs1);
}
// RV32-LABEL: @test_pncvth_u8x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <4 x i8> @llvm.riscv.pnsrl.v4i8(i64 [[RS1_COERCE:%.*]], i32 8)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <4 x i8> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint8x4_t test_pncvth_u8x4(uint16x4_t rs1) {
  return __riscv_pncvth_u8x4(rs1);
}
// RV32-LABEL: @test_pncvth_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <2 x i16> @llvm.riscv.pnsrl.v2i16(i64 [[RS1_COERCE:%.*]], i32 16)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
int16x2_t test_pncvth_i16x2(int32x2_t rs1) {
  return __riscv_pncvth_i16x2(rs1);
}
// RV32-LABEL: @test_pncvth_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call <2 x i16> @llvm.riscv.pnsrl.v2i16(i64 [[RS1_COERCE:%.*]], i32 16)
// RV32-NEXT:    [[TMP1:%.*]] = bitcast <2 x i16> [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
uint16x2_t test_pncvth_u16x2(uint32x2_t rs1) {
  return __riscv_pncvth_u16x2(rs1);
}
