// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_pjoin2_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[LO_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[HI_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t   test_pjoin2_i8x8(int8x4_t lo, int8x4_t hi)     { return __riscv_pjoin2_i8x8(lo, hi); }
// RV64-LABEL: @test_pjoin2_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[LO_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[HI_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t  test_pjoin2_u8x8(uint8x4_t lo, uint8x4_t hi)   { return __riscv_pjoin2_u8x8(lo, hi); }
// RV64-LABEL: @test_pjoin2_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[LO_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[HI_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> [[TMP1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t  test_pjoin2_i16x4(int16x2_t lo, int16x2_t hi)  { return __riscv_pjoin2_i16x4(lo, hi); }
// RV64-LABEL: @test_pjoin2_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[LO_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[HI_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> [[TMP1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pjoin2_u16x4(uint16x2_t lo, uint16x2_t hi) { return __riscv_pjoin2_u16x4(lo, hi); }
