// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// Halfword scalar form (cross-XLEN, mapped to pmqacc.w.h on RV64).
// RV64-LABEL: @test_mqacc_h00_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT3_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RD:%.*]], i64 0
// RV64-NEXT:    [[VECINIT8_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT14_I:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP4:%.*]] = call <2 x i32> @llvm.riscv.pmqacc.h00.v2i32.v4i16(<2 x i32> [[VECINIT3_I]], <4 x i16> [[VECINIT8_I]], <4 x i16> [[VECINIT14_I]])
// RV64-NEXT:    [[VECEXT15_I:%.*]] = extractelement <2 x i32> [[TMP4]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT15_I]]
//
int32_t test_mqacc_h00_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqacc_h00_i32(rd, rs1, rs2);
}
// RV64-LABEL: @test_mqracc_h00_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT3_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RD:%.*]], i64 0
// RV64-NEXT:    [[VECINIT8_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT14_I:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP4:%.*]] = call <2 x i32> @llvm.riscv.pmqracc.h00.v2i32.v4i16(<2 x i32> [[VECINIT3_I]], <4 x i16> [[VECINIT8_I]], <4 x i16> [[VECINIT14_I]])
// RV64-NEXT:    [[VECEXT15_I:%.*]] = extractelement <2 x i32> [[TMP4]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT15_I]]
//
int32_t test_mqracc_h00_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_mqracc_h00_i32(rd, rs1, rs2);
}

// Halfword vector form (RV64 only, pmqacc.w.h* / pmqracc.w.h*).
// RV64-LABEL: @test_pmqacc_h00_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmqacc.h00.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmqacc_h00_i32x2(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmqacc_h00_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmqacc_h01_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmqacc.h01.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmqacc_h01_i32x2(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmqacc_h01_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmqacc_h11_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmqacc.h11.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmqacc_h11_i32x2(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmqacc_h11_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmqracc_h00_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmqracc.h00.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmqracc_h00_i32x2(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmqracc_h00_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmqracc_h01_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmqracc.h01.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmqracc_h01_i32x2(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmqracc_h01_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmqracc_h11_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmqracc.h11.v2i32.v4i16(<2 x i32> [[TMP0]], <4 x i16> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmqracc_h11_i32x2(int32x2_t rd, int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmqracc_h11_i32x2(rd, rs1, rs2);
}

// Word scalar form (RV64 only, mqacc.w* / mqracc.w*).
// RV64-LABEL: @test_mqacc_w00_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqacc.w00.i64.v2i32(i64 [[RD:%.*]], <2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mqacc_w00_i64(int64_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mqacc_w00_i64(rd, rs1, rs2);
}
// RV64-LABEL: @test_mqacc_w01_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqacc.w01.i64.v2i32(i64 [[RD:%.*]], <2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mqacc_w01_i64(int64_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mqacc_w01_i64(rd, rs1, rs2);
}
// RV64-LABEL: @test_mqacc_w11_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqacc.w11.i64.v2i32(i64 [[RD:%.*]], <2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mqacc_w11_i64(int64_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mqacc_w11_i64(rd, rs1, rs2);
}
// RV64-LABEL: @test_mqracc_w00_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqracc.w00.i64.v2i32(i64 [[RD:%.*]], <2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mqracc_w00_i64(int64_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mqracc_w00_i64(rd, rs1, rs2);
}
// RV64-LABEL: @test_mqracc_w01_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqracc.w01.i64.v2i32(i64 [[RD:%.*]], <2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mqracc_w01_i64(int64_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mqracc_w01_i64(rd, rs1, rs2);
}
// RV64-LABEL: @test_mqracc_w11_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pmqracc.w11.i64.v2i32(i64 [[RD:%.*]], <2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t test_mqracc_w11_i64(int64_t rd, int32x2_t rs1, int32x2_t rs2) {
  return __riscv_mqracc_w11_i64(rd, rs1, rs2);
}
