// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pmhacc_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV32-NEXT:    [[CONV4_I:%.*]] = sext <2 x i16> [[TMP2]] to <2 x i32>
// RV32-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV32-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV32-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV32-NEXT:    [[ADD_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD_I]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhacc_i16x2(int16x2_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmhacc_i16x2(rd, rs1, rs2);
}

// RV32-LABEL: @test_pmhracc_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV32-NEXT:    [[CONV4_I:%.*]] = sext <2 x i16> [[TMP2]] to <2 x i32>
// RV32-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV32-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV32-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV32-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV32-NEXT:    [[ADD6_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD6_I]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhracc_i16x2(int16x2_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmhracc_i16x2(rd, rs1, rs2);
}

// RV32-LABEL: @test_pmhaccu_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[CONV_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV32-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV32-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV32-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV32-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV32-NEXT:    [[ADD_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD_I]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmhaccu_u16x2(uint16x2_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhaccu_u16x2(rd, rs1, rs2);
}

// RV32-LABEL: @test_pmhraccu_u16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[CONV_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV32-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV32-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV32-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV32-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV32-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV32-NEXT:    [[ADD6_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD6_I]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
uint16x2_t test_pmhraccu_u16x2(uint16x2_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhraccu_u16x2(rd, rs1, rs2);
}

// RV32-LABEL: @test_pmhaccsu_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV32-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV32-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV32-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV32-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV32-NEXT:    [[ADD_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD_I]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhaccsu_i16x2(int16x2_t rd, int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhaccsu_i16x2(rd, rs1, rs2);
}

// RV32-LABEL: @test_pmhraccsu_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV32-NEXT:    [[CONV4_I:%.*]] = zext <2 x i16> [[TMP2]] to <2 x i32>
// RV32-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV4_I]]
// RV32-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV32-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV32-NEXT:    [[CONV5_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV32-NEXT:    [[ADD6_I:%.*]] = add <2 x i16> [[TMP0]], [[CONV5_I]]
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[ADD6_I]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmhraccsu_i16x2(int16x2_t rd, int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmhraccsu_i16x2(rd, rs1, rs2);
}
