// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pmulh_b0_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulh.b0.v2i16.v4i8(<2 x i16> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmulh_b0_i16x2(int16x2_t rs1, int8x4_t rs2) {
  return __riscv_pmulh_b0_i16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulh_b1_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulh.b1.v2i16.v4i8(<2 x i16> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmulh_b1_i16x2(int16x2_t rs1, int8x4_t rs2) {
  return __riscv_pmulh_b1_i16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulhsu_b0_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulhsu.b0.v2i16.v4i8(<2 x i16> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmulhsu_b0_i16x2(int16x2_t rs1, uint8x4_t rs2) {
  return __riscv_pmulhsu_b0_i16x2(rs1, rs2);
}
// RV32-LABEL: @test_pmulhsu_b1_i16x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call <2 x i16> @llvm.riscv.pmulhsu.b1.v2i16.v4i8(<2 x i16> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16> [[TMP2]] to i32
// RV32-NEXT:    ret i32 [[TMP3]]
//
int16x2_t test_pmulhsu_b1_i16x2(int16x2_t rs1, uint8x4_t rs2) {
  return __riscv_pmulhsu_b1_i16x2(rs1, rs2);
}

// RV32-LABEL: @test_mulh_h0_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmulh.h0.i32.v2i16(i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mulh_h0_i32(int32_t rs1, int16x2_t rs2) {
  return __riscv_mulh_h0_i32(rs1, rs2);
}
// RV32-LABEL: @test_mulh_h1_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmulh.h1.i32.v2i16(i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mulh_h1_i32(int32_t rs1, int16x2_t rs2) {
  return __riscv_mulh_h1_i32(rs1, rs2);
}
// RV32-LABEL: @test_mulhsu_h0_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmulhsu.h0.i32.v2i16(i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mulhsu_h0_i32(int32_t rs1, uint16x2_t rs2) {
  return __riscv_mulhsu_h0_i32(rs1, rs2);
}
// RV32-LABEL: @test_mulhsu_h1_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.riscv.pmulhsu.h1.i32.v2i16(i32 [[RS1:%.*]], <2 x i16> [[TMP0]])
// RV32-NEXT:    ret i32 [[TMP1]]
//
int32_t test_mulhsu_h1_i32(int32_t rs1, uint16x2_t rs2) {
  return __riscv_mulhsu_h1_i32(rs1, rs2);
}
