// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pwadd_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwadd.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwadd_i16x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pwadd_i16x4(rs1, rs2);
}
// RV32-LABEL: @test_pwadd_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwadd.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwadd_i32x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pwadd_i32x2(rs1, rs2);
}
// RV32-LABEL: @test_pwaddu_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwaddu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwaddu_u16x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pwaddu_u16x4(rs1, rs2);
}
// RV32-LABEL: @test_pwaddu_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwaddu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwaddu_u32x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pwaddu_u32x2(rs1, rs2);
}
// RV32-LABEL: @test_pwsub_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsub.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwsub_i16x4(int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pwsub_i16x4(rs1, rs2);
}
// RV32-LABEL: @test_pwsub_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsub.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwsub_i32x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pwsub_i32x2(rs1, rs2);
}
// RV32-LABEL: @test_pwsubu_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsubu.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwsubu_u16x4(uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pwsubu_u16x4(rs1, rs2);
}
// RV32-LABEL: @test_pwsubu_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsubu.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwsubu_u32x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pwsubu_u32x2(rs1, rs2);
}
