// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=mem2reg,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_asub_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.asub.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_asub_i32(int32_t a, int32_t b)        { return __riscv_asub_i32(a, b); }
// RV64-LABEL: @test_asubu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.asubu.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_asubu_u32(uint32_t a, uint32_t b)     { return __riscv_asubu_u32(a, b); }

// RV64-LABEL: @test_sati_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.sati.i32.i64(i64 [[TMP0]], i32 12)
// RV64-NEXT:    [[TMP2:%.*]] = trunc i64 [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int32_t  test_sati_i32(int32_t a)                   { return __riscv_sati_i32(a, 12); }
// RV64-LABEL: @test_usati_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = call i64 @llvm.riscv.usati.i32.i64(i64 [[TMP0]], i32 12)
// RV64-NEXT:    [[TMP2:%.*]] = trunc i64 [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
uint32_t test_usati_u32(int32_t a)                  { return __riscv_usati_u32(a, 12); }

// RV64-LABEL: @test_ssh1sadd_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.ssh1sadd.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_ssh1sadd_i32(int32_t a, int32_t b)    { return __riscv_ssh1sadd_i32(a, b); }

// RV64-LABEL: @test_mulhr_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mulhr.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_mulhr_i32(int32_t a, int32_t b)       { return __riscv_mulhr_i32(a, b); }
// RV64-LABEL: @test_mulhru_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mulhru.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_mulhru_u32(uint32_t a, uint32_t b)    { return __riscv_mulhru_u32(a, b); }
// RV64-LABEL: @test_mulhrsu_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mulhrsu.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_mulhrsu_i32(int32_t a, uint32_t b)    { return __riscv_mulhrsu_i32(a, b); }

// RV64-LABEL: @test_mhacc_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[RD:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.mhacc.i32.i64(i64 [[TMP0]], i64 [[TMP1]], i64 [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
int32_t  test_mhacc_i32(int32_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mhacc_i32(rd, a, b); }
// RV64-LABEL: @test_mhracc_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[RD:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.mhracc.i32.i64(i64 [[TMP0]], i64 [[TMP1]], i64 [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
int32_t  test_mhracc_i32(int32_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mhracc_i32(rd, a, b); }
// RV64-LABEL: @test_mhaccu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[RD:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.mhaccu.i32.i64(i64 [[TMP0]], i64 [[TMP1]], i64 [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint32_t test_mhaccu_u32(uint32_t rd, uint32_t a, uint32_t b)
                                                    { return __riscv_mhaccu_u32(rd, a, b); }
// RV64-LABEL: @test_mhraccu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[RD:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.mhraccu.i32.i64(i64 [[TMP0]], i64 [[TMP1]], i64 [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
uint32_t test_mhraccu_u32(uint32_t rd, uint32_t a, uint32_t b)
                                                    { return __riscv_mhraccu_u32(rd, a, b); }
// RV64-LABEL: @test_mhaccsu_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[RD:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.mhaccsu.i32.i64(i64 [[TMP0]], i64 [[TMP1]], i64 [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
int32_t  test_mhaccsu_i32(int32_t rd, int32_t a, uint32_t b)
                                                    { return __riscv_mhaccsu_i32(rd, a, b); }
// RV64-LABEL: @test_mhraccsu_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[RD:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.mhraccsu.i32.i64(i64 [[TMP0]], i64 [[TMP1]], i64 [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
// RV64-NEXT:    ret i32 [[TMP4]]
//
int32_t  test_mhraccsu_i32(int32_t rd, int32_t a, uint32_t b)
                                                    { return __riscv_mhraccsu_i32(rd, a, b); }

// RV64-LABEL: @test_mulq_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mulq.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_mulq_i32(int32_t a, int32_t b)        { return __riscv_mulq_i32(a, b); }
// RV64-LABEL: @test_mulqr_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mulqr.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_mulqr_i32(int32_t a, int32_t b)       { return __riscv_mulqr_i32(a, b); }

// RV64-LABEL: @test_mqwacc_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mqwacc.i64.i64(i64 [[RD:%.*]], i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t  test_mqwacc_i64(int64_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mqwacc_i64(rd, a, b); }
// RV64-LABEL: @test_mqrwacc_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mqrwacc.i64.i64(i64 [[RD:%.*]], i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    ret i64 [[TMP2]]
//
int64_t  test_mqrwacc_i64(int64_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mqrwacc_i64(rd, a, b); }

// RV64-LABEL: @test_mseq_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mseq.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
int32_t  test_mseq_i32(int32_t a, int32_t b)        { return __riscv_mseq_i32(a, b); }
// RV64-LABEL: @test_mseq_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mseq.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_mseq_u32(uint32_t a, uint32_t b)      { return __riscv_mseq_u32(a, b); }
// RV64-LABEL: @test_mslt_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mslt.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_mslt_u32(int32_t a, int32_t b)        { return __riscv_mslt_u32(a, b); }
// RV64-LABEL: @test_msgt_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.mslt.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_msgt_u32(int32_t a, int32_t b)        { return __riscv_msgt_u32(a, b); }
// RV64-LABEL: @test_msltu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.msltu.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_msltu_u32(uint32_t a, uint32_t b)     { return __riscv_msltu_u32(a, b); }
// RV64-LABEL: @test_msgtu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.msltu.i32.i64(i64 [[TMP0]], i64 [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
// RV64-NEXT:    ret i32 [[TMP3]]
//
uint32_t test_msgtu_u32(uint32_t a, uint32_t b)     { return __riscv_msgtu_u32(a, b); }

// RV64-LABEL: @test_rev16_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.rev16.i64(i64 [[A:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_rev16_64(uint64_t a)                  { return __riscv_rev16_64(a); }

// RV64-LABEL: @test_sati_i64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sati.i64.i64(i64 [[A:%.*]], i32 16)
// RV64-NEXT:    ret i64 [[TMP0]]
//
int64_t  test_sati_i64(int64_t a)                   { return __riscv_sati_i64(a, 16); }
// RV64-LABEL: @test_usati_u64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.usati.i64.i64(i64 [[A:%.*]], i32 16)
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_usati_u64(int64_t a)                  { return __riscv_usati_u64(a, 16); }

// RV64-LABEL: @test_zip8p_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.zip8p.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_zip8p_64(uint64_t a, uint64_t b)      { return __riscv_zip8p_64(a, b); }
// RV64-LABEL: @test_zip16p_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.zip16p.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_zip16p_64(uint64_t a, uint64_t b)     { return __riscv_zip16p_64(a, b); }
// RV64-LABEL: @test_zip8hp_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.zip8hp.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_zip8hp_64(uint64_t a, uint64_t b)     { return __riscv_zip8hp_64(a, b); }
// RV64-LABEL: @test_zip16hp_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.zip16hp.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_zip16hp_64(uint64_t a, uint64_t b)    { return __riscv_zip16hp_64(a, b); }

// RV64-LABEL: @test_unzip8p_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.unzip8p.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_unzip8p_64(uint64_t a, uint64_t b)    { return __riscv_unzip8p_64(a, b); }
// RV64-LABEL: @test_unzip16p_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.unzip16p.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_unzip16p_64(uint64_t a, uint64_t b)   { return __riscv_unzip16p_64(a, b); }
// RV64-LABEL: @test_unzip8hp_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.unzip8hp.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_unzip8hp_64(uint64_t a, uint64_t b)   { return __riscv_unzip8hp_64(a, b); }
// RV64-LABEL: @test_unzip16hp_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.unzip16hp.64(i64 [[A:%.*]], i64 [[B:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_unzip16hp_64(uint64_t a, uint64_t b)  { return __riscv_unzip16hp_64(a, b); }
