// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_pwadda_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwadda.v4i8(i64 [[RD_COERCE:%.*]], <4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwadda_i16x4(int16x4_t rd, int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pwadda_i16x4(rd, rs1, rs2);
}
// RV32-LABEL: @test_pwadda_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwadda.v2i16(i64 [[RD_COERCE:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwadda_i32x2(int32x2_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pwadda_i32x2(rd, rs1, rs2);
}
// RV32-LABEL: @test_pwaddau_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwaddau.v4i8(i64 [[RD_COERCE:%.*]], <4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwaddau_u16x4(uint16x4_t rd, uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pwaddau_u16x4(rd, rs1, rs2);
}
// RV32-LABEL: @test_pwaddau_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwaddau.v2i16(i64 [[RD_COERCE:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwaddau_u32x2(uint32x2_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pwaddau_u32x2(rd, rs1, rs2);
}
// RV32-LABEL: @test_pwsuba_i16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsuba.v4i8(i64 [[RD_COERCE:%.*]], <4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pwsuba_i16x4(int16x4_t rd, int8x4_t rs1, int8x4_t rs2) {
  return __riscv_pwsuba_i16x4(rd, rs1, rs2);
}
// RV32-LABEL: @test_pwsuba_i32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsuba.v2i16(i64 [[RD_COERCE:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pwsuba_i32x2(int32x2_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pwsuba_i32x2(rd, rs1, rs2);
}
// RV32-LABEL: @test_pwsubau_u16x4(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsubau.v4i8(i64 [[RD_COERCE:%.*]], <4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pwsubau_u16x4(uint16x4_t rd, uint8x4_t rs1, uint8x4_t rs2) {
  return __riscv_pwsubau_u16x4(rd, rs1, rs2);
}
// RV32-LABEL: @test_pwsubau_u32x2(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pwsubau.v2i16(i64 [[RD_COERCE:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pwsubau_u32x2(uint32x2_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pwsubau_u32x2(rd, rs1, rs2);
}
