// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_pnzip_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pnzip.v8i8.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_pnzip_i8x8(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pnzip_i8x8(rs1, rs2);
}
// RV64-LABEL: @test_pnzip_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pnzip.v8i8.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_pnzip_u8x8(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pnzip_u8x8(rs1, rs2);
}
// RV64-LABEL: @test_pnzip_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pnzip.v4i16.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pnzip_i16x4(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pnzip_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pnzip_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pnzip.v4i16.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pnzip_u16x4(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pnzip_u16x4(rs1, rs2);
}
// RV64-LABEL: @test_pnziph_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pnziph.v8i8.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_pnziph_i8x8(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pnziph_i8x8(rs1, rs2);
}
// RV64-LABEL: @test_pnziph_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = call <8 x i8> @llvm.riscv.pnziph.v8i8.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <8 x i8> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_pnziph_u8x8(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pnziph_u8x8(rs1, rs2);
}
// RV64-LABEL: @test_pnziph_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pnziph.v4i16.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_pnziph_i16x4(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pnziph_i16x4(rs1, rs2);
}
// RV64-LABEL: @test_pnziph_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = call <4 x i16> @llvm.riscv.pnziph.v4i16.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// RV64-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[TMP2]] to i64
// RV64-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_pnziph_u16x4(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pnziph_u16x4(rs1, rs2);
}
