// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_macc_h00_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmacc.h00.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_macc_h00_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_macc_h00_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_macc_h01_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmacc.h01.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_macc_h01_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_macc_h01_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_macc_h11_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmacc.h11.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_macc_h11_i32(int32_t rd, int16x2_t rs1, int16x2_t rs2) {
  return __riscv_macc_h11_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_maccu_h00_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmaccu.h00.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint32_t test_maccu_h00_u32(uint32_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_maccu_h00_u32(rd, rs1, rs2);
}
// RV32-LABEL: @test_maccu_h01_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmaccu.h01.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint32_t test_maccu_h01_u32(uint32_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_maccu_h01_u32(rd, rs1, rs2);
}
// RV32-LABEL: @test_maccu_h11_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmaccu.h11.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
uint32_t test_maccu_h11_u32(uint32_t rd, uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_maccu_h11_u32(rd, rs1, rs2);
}
// RV32-LABEL: @test_maccsu_h00_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmaccsu.h00.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_maccsu_h00_i32(int32_t rd, int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_maccsu_h00_i32(rd, rs1, rs2);
}
// RV32-LABEL: @test_maccsu_h11_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i32 @llvm.riscv.pmaccsu.h11.i32.v2i16(i32 [[RD:%.*]], <2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i32 [[TMP2]]
//
int32_t test_maccsu_h11_i32(int32_t rd, int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_maccsu_h11_i32(rd, rs1, rs2);
}
