// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_pmulh_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP0]] to <2 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[CONV4_I]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int16x2_t test_pmulh_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmulh_i16x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhr_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP0]] to <2 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = sext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[CONV4_I]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int16x2_t test_pmulhr_i16x2(int16x2_t rs1, int16x2_t rs2) {
  return __riscv_pmulhr_i16x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhu_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i16> [[TMP0]] to <2 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[CONV4_I]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
uint16x2_t test_pmulhu_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmulhu_u16x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhru_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i16> [[TMP0]] to <2 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[CONV4_I]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
uint16x2_t test_pmulhru_u16x2(uint16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmulhru_u16x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhsu_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP0]] to <2 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[CONV4_I]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int16x2_t test_pmulhsu_i16x2(int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmulhsu_i16x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhrsu_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i16> [[TMP0]] to <2 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i16> [[TMP1]] to <2 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i32> [[SHR_I]] to <2 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[CONV4_I]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int16x2_t test_pmulhrsu_i16x2(int16x2_t rs1, uint16x2_t rs2) {
  return __riscv_pmulhrsu_i16x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulh_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP0]] to <4 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = sext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pmulh_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmulh_i16x4(rs1, rs2);
}

// RV64-LABEL: @test_pmulhr_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP0]] to <4 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = sext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pmulhr_i16x4(int16x4_t rs1, int16x4_t rs2) {
  return __riscv_pmulhr_i16x4(rs1, rs2);
}

// RV64-LABEL: @test_pmulhu_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <4 x i16> [[TMP0]] to <4 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <4 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pmulhu_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulhu_u16x4(rs1, rs2);
}

// RV64-LABEL: @test_pmulhru_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <4 x i16> [[TMP0]] to <4 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <4 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pmulhru_u16x4(uint16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulhru_u16x4(rs1, rs2);
}

// RV64-LABEL: @test_pmulhsu_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP0]] to <4 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[MUL_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pmulhsu_i16x4(int16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulhsu_i16x4(rs1, rs2);
}

// RV64-LABEL: @test_pmulhrsu_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <4 x i16> [[TMP0]] to <4 x i32>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <4 x i16> [[TMP1]] to <4 x i32>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <4 x i32> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <4 x i32> [[MUL_I]], splat (i32 32768)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <4 x i32> [[ADD_I]], splat (i32 16)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <4 x i32> [[SHR_I]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t test_pmulhrsu_i16x4(int16x4_t rs1, uint16x4_t rs2) {
  return __riscv_pmulhrsu_i16x4(rs1, rs2);
}

// RV64-LABEL: @test_pmulh_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP0]] to <2 x i64>
// RV64-NEXT:    [[CONV3_I:%.*]] = sext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[MUL_I]], splat (i64 32)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pmulh_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmulh_i32x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhr_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP0]] to <2 x i64>
// RV64-NEXT:    [[CONV3_I:%.*]] = sext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i64> [[MUL_I]], splat (i64 2147483648)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[ADD_I]], splat (i64 32)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pmulhr_i32x2(int32x2_t rs1, int32x2_t rs2) {
  return __riscv_pmulhr_i32x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhu_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i32> [[TMP0]] to <2 x i64>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i64> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[MUL_I]], splat (i64 32)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pmulhu_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmulhu_u32x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhru_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = zext <2 x i32> [[TMP0]] to <2 x i64>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw <2 x i64> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i64> [[MUL_I]], splat (i64 2147483648)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[ADD_I]], splat (i64 32)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pmulhru_u32x2(uint32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmulhru_u32x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhsu_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP0]] to <2 x i64>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[MUL_I]], splat (i64 32)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pmulhsu_i32x2(int32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmulhsu_i32x2(rs1, rs2);
}

// RV64-LABEL: @test_pmulhrsu_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[CONV_I:%.*]] = sext <2 x i32> [[TMP0]] to <2 x i64>
// RV64-NEXT:    [[CONV3_I:%.*]] = zext <2 x i32> [[TMP1]] to <2 x i64>
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw <2 x i64> [[CONV_I]], [[CONV3_I]]
// RV64-NEXT:    [[ADD_I:%.*]] = add <2 x i64> [[MUL_I]], splat (i64 2147483648)
// RV64-NEXT:    [[SHR_I:%.*]] = lshr <2 x i64> [[ADD_I]], splat (i64 32)
// RV64-NEXT:    [[CONV4_I:%.*]] = trunc nuw <2 x i64> [[SHR_I]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[CONV4_I]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t test_pmulhrsu_i32x2(int32x2_t rs1, uint32x2_t rs2) {
  return __riscv_pmulhrsu_i32x2(rs1, rs2);
}
