// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// RV64-LABEL: @test_aadd_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[CONV_I:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[CONV1_I:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[ADD_I:%.*]] = add nsw i64 [[CONV_I]], [[CONV1_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr i64 [[ADD_I]], 1
// RV64-NEXT:    [[CONV2_I:%.*]] = trunc i64 [[SHR_I]] to i32
// RV64-NEXT:    ret i32 [[CONV2_I]]
//
int32_t  test_aadd_i32(int32_t a, int32_t b)    { return __riscv_aadd_i32(a, b); }
// RV64-LABEL: @test_aaddu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[CONV_I:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[CONV1_I:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[ADD_I:%.*]] = add nuw nsw i64 [[CONV_I]], [[CONV1_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr i64 [[ADD_I]], 1
// RV64-NEXT:    [[CONV2_I:%.*]] = trunc nuw i64 [[SHR_I]] to i32
// RV64-NEXT:    ret i32 [[CONV2_I]]
//
uint32_t test_aaddu_u32(uint32_t a, uint32_t b) { return __riscv_aaddu_u32(a, b); }
// RV64-LABEL: @test_mulh_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[CONV_I:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[CONV1_I:%.*]] = sext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw i64 [[CONV_I]], [[CONV1_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr i64 [[MUL_I]], 32
// RV64-NEXT:    [[CONV2_I:%.*]] = trunc nuw i64 [[SHR_I]] to i32
// RV64-NEXT:    ret i32 [[CONV2_I]]
//
int32_t  test_mulh_i32(int32_t a, int32_t b)    { return __riscv_mulh_i32(a, b); }
// RV64-LABEL: @test_mulhu_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[CONV_I:%.*]] = zext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[CONV1_I:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[MUL_I:%.*]] = mul nuw i64 [[CONV_I]], [[CONV1_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr i64 [[MUL_I]], 32
// RV64-NEXT:    [[CONV2_I:%.*]] = trunc nuw i64 [[SHR_I]] to i32
// RV64-NEXT:    ret i32 [[CONV2_I]]
//
uint32_t test_mulhu_u32(uint32_t a, uint32_t b) { return __riscv_mulhu_u32(a, b); }
// RV64-LABEL: @test_mulhsu_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[CONV_I:%.*]] = sext i32 [[A:%.*]] to i64
// RV64-NEXT:    [[CONV1_I:%.*]] = zext i32 [[B:%.*]] to i64
// RV64-NEXT:    [[MUL_I:%.*]] = mul nsw i64 [[CONV_I]], [[CONV1_I]]
// RV64-NEXT:    [[SHR_I:%.*]] = lshr i64 [[MUL_I]], 32
// RV64-NEXT:    [[CONV2_I:%.*]] = trunc nuw i64 [[SHR_I]] to i32
// RV64-NEXT:    ret i32 [[CONV2_I]]
//
int32_t  test_mulhsu_i32(int32_t a, uint32_t b) { return __riscv_mulhsu_i32(a, b); }
