// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=mem2reg,instcombine | FileCheck %s --check-prefix=RV32

#include <riscv_packed.h>

// RV32-LABEL: @test_asub_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.asub.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_asub_i32(int32_t a, int32_t b)        { return __riscv_asub_i32(a, b); }
// RV32-LABEL: @test_asubu_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.asubu.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_asubu_u32(uint32_t a, uint32_t b)     { return __riscv_asubu_u32(a, b); }

// RV32-LABEL: @test_sati_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sati.i32.i32(i32 [[A:%.*]], i32 12)
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_sati_i32(int32_t a)                   { return __riscv_sati_i32(a, 12); }
// RV32-LABEL: @test_usati_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.usati.i32.i32(i32 [[A:%.*]], i32 12)
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_usati_u32(int32_t a)                  { return __riscv_usati_u32(a, 12); }

// RV32-LABEL: @test_ssh1sadd_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ssh1sadd.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_ssh1sadd_i32(int32_t a, int32_t b)    { return __riscv_ssh1sadd_i32(a, b); }

// RV32-LABEL: @test_mulhr_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhr.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mulhr_i32(int32_t a, int32_t b)       { return __riscv_mulhr_i32(a, b); }
// RV32-LABEL: @test_mulhru_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhru.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_mulhru_u32(uint32_t a, uint32_t b)    { return __riscv_mulhru_u32(a, b); }
// RV32-LABEL: @test_mulhrsu_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhrsu.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mulhrsu_i32(int32_t a, uint32_t b)    { return __riscv_mulhrsu_i32(a, b); }

// RV32-LABEL: @test_mhacc_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mhacc.i32.i32(i32 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mhacc_i32(int32_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mhacc_i32(rd, a, b); }
// RV32-LABEL: @test_mhracc_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mhracc.i32.i32(i32 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mhracc_i32(int32_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mhracc_i32(rd, a, b); }
// RV32-LABEL: @test_mhaccu_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mhaccu.i32.i32(i32 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_mhaccu_u32(uint32_t rd, uint32_t a, uint32_t b)
                                                    { return __riscv_mhaccu_u32(rd, a, b); }
// RV32-LABEL: @test_mhraccu_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mhraccu.i32.i32(i32 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_mhraccu_u32(uint32_t rd, uint32_t a, uint32_t b)
                                                    { return __riscv_mhraccu_u32(rd, a, b); }
// RV32-LABEL: @test_mhaccsu_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mhaccsu.i32.i32(i32 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mhaccsu_i32(int32_t rd, int32_t a, uint32_t b)
                                                    { return __riscv_mhaccsu_i32(rd, a, b); }
// RV32-LABEL: @test_mhraccsu_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mhraccsu.i32.i32(i32 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mhraccsu_i32(int32_t rd, int32_t a, uint32_t b)
                                                    { return __riscv_mhraccsu_i32(rd, a, b); }

// RV32-LABEL: @test_mulq_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulq.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mulq_i32(int32_t a, int32_t b)        { return __riscv_mulq_i32(a, b); }
// RV32-LABEL: @test_mulqr_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulqr.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mulqr_i32(int32_t a, int32_t b)       { return __riscv_mulqr_i32(a, b); }

// RV32-LABEL: @test_mqwacc_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.mqwacc.i64.i32(i64 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i64 [[TMP0]]
//
int64_t  test_mqwacc_i64(int64_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mqwacc_i64(rd, a, b); }
// RV32-LABEL: @test_mqrwacc_i64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.mqrwacc.i64.i32(i64 [[RD:%.*]], i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i64 [[TMP0]]
//
int64_t  test_mqrwacc_i64(int64_t rd, int32_t a, int32_t b)
                                                    { return __riscv_mqrwacc_i64(rd, a, b); }

// RV32-LABEL: @test_mseq_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mseq.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_mseq_i32(int32_t a, int32_t b)        { return __riscv_mseq_i32(a, b); }
// RV32-LABEL: @test_mseq_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mseq.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_mseq_u32(uint32_t a, uint32_t b)      { return __riscv_mseq_u32(a, b); }
// RV32-LABEL: @test_mslt_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mslt.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_mslt_u32(int32_t a, int32_t b)        { return __riscv_mslt_u32(a, b); }
// RV32-LABEL: @test_msgt_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mslt.i32.i32(i32 [[B:%.*]], i32 [[A:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_msgt_u32(int32_t a, int32_t b)        { return __riscv_msgt_u32(a, b); }
// RV32-LABEL: @test_msltu_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.msltu.i32.i32(i32 [[A:%.*]], i32 [[B:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_msltu_u32(uint32_t a, uint32_t b)     { return __riscv_msltu_u32(a, b); }
// RV32-LABEL: @test_msgtu_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.msltu.i32.i32(i32 [[B:%.*]], i32 [[A:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_msgtu_u32(uint32_t a, uint32_t b)     { return __riscv_msgtu_u32(a, b); }

// RV32-LABEL: @test_wzip8p_64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[A:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[B:%.*]] to <4 x i8>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pzip.v4i8(<4 x i8> [[TMP0]], <4 x i8> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint64_t test_wzip8p_64(uint32_t a, uint32_t b)     { return __riscv_wzip8p_64(a, b); }
// RV32-LABEL: @test_wzip16p_64(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = bitcast i32 [[A:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP1:%.*]] = bitcast i32 [[B:%.*]] to <2 x i16>
// RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.pzip.v2i16(<2 x i16> [[TMP0]], <2 x i16> [[TMP1]])
// RV32-NEXT:    ret i64 [[TMP2]]
//
uint64_t test_wzip16p_64(uint32_t a, uint32_t b)    { return __riscv_wzip16p_64(a, b); }

// RV32-LABEL: @test_nclipu_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pnclipu.i32(i64 [[P:%.*]], i32 [[S:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_nclipu_u32(uint64_t p, unsigned s)    { return __riscv_nclipu_u32(p, s); }
// RV32-LABEL: @test_nclipru_u32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pnclipru.i32(i64 [[P:%.*]], i32 [[S:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_nclipru_u32(uint64_t p, unsigned s)   { return __riscv_nclipru_u32(p, s); }
// RV32-LABEL: @test_nclip_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pnclip.i32(i64 [[P:%.*]], i32 [[S:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_nclip_i32(int64_t p, unsigned s)      { return __riscv_nclip_i32(p, s); }
// RV32-LABEL: @test_nclipr_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pnclipr.i32(i64 [[P:%.*]], i32 [[S:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_nclipr_i32(int64_t p, unsigned s)     { return __riscv_nclipr_i32(p, s); }
// RV32-LABEL: @test_nsrar_i32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pnsrar.i32(i64 [[P:%.*]], i32 [[S:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_nsrar_i32(int64_t p, unsigned s)      { return __riscv_nsrar_i32(p, s); }
