// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

/* 32-bit table */
// RV64-LABEL: @test_pget_i8x4_i8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i32 [[V_COERCE:%.*]], 16
// RV64-NEXT:    [[TMP0:%.*]] = trunc i32 [[EXTELT_OFFSET]] to i8
// RV64-NEXT:    ret i8 [[TMP0]]
//
int8_t   test_pget_i8x4_i8(int8x4_t v)     { return __riscv_pget_i8x4_i8(v, 2); }
// RV64-LABEL: @test_pget_u8x4_u8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i32 [[V_COERCE:%.*]], 24
// RV64-NEXT:    [[TMP0:%.*]] = trunc nuw i32 [[EXTELT_OFFSET]] to i8
// RV64-NEXT:    ret i8 [[TMP0]]
//
uint8_t  test_pget_u8x4_u8(uint8x4_t v)    { return __riscv_pget_u8x4_u8(v, 3); }
// RV64-LABEL: @test_pget_i16x2_i16(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i32 [[V_COERCE:%.*]], 16
// RV64-NEXT:    [[TMP0:%.*]] = trunc nuw i32 [[EXTELT_OFFSET]] to i16
// RV64-NEXT:    ret i16 [[TMP0]]
//
int16_t  test_pget_i16x2_i16(int16x2_t v)  { return __riscv_pget_i16x2_i16(v, 1); }
// RV64-LABEL: @test_pget_u16x2_u16(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = trunc i32 [[V_COERCE:%.*]] to i16
// RV64-NEXT:    ret i16 [[TMP0]]
//
uint16_t test_pget_u16x2_u16(uint16x2_t v) { return __riscv_pget_u16x2_u16(v, 0); }
// RV64-LABEL: @test_pset_i8_i8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[V_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i8> [[TMP0]], i8 [[E:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i8> [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int8x4_t   test_pset_i8_i8x4(int8x4_t v,     int8_t e)   { return __riscv_pset_i8_i8x4(v, e, 1); }
// RV64-LABEL: @test_pset_u8_u8x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[V_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i8> [[TMP0]], i8 [[E:%.*]], i64 2
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i8> [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
uint8x4_t  test_pset_u8_u8x4(uint8x4_t v,    uint8_t e)  { return __riscv_pset_u8_u8x4(v, e, 2); }
// RV64-LABEL: @test_pset_i16_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[V_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <2 x i16> [[TMP0]], i16 [[E:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i16> [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int16x2_t  test_pset_i16_i16x2(int16x2_t v,  int16_t e)  { return __riscv_pset_i16_i16x2(v, e, 1); }
// RV64-LABEL: @test_pset_u16_u16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = and i32 [[V_COERCE:%.*]], -65536
// RV64-NEXT:    [[TMP1:%.*]] = zext i16 [[E:%.*]] to i32
// RV64-NEXT:    [[TMP2:%.*]] = or disjoint i32 [[TMP0]], [[TMP1]]
// RV64-NEXT:    ret i32 [[TMP2]]
//
uint16x2_t test_pset_u16_u16x2(uint16x2_t v, uint16_t e) { return __riscv_pset_u16_u16x2(v, e, 0); }

/* 64-bit table */
// RV64-LABEL: @test_pget_i8x8_i8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 40
// RV64-NEXT:    [[TMP0:%.*]] = trunc i64 [[EXTELT_OFFSET]] to i8
// RV64-NEXT:    ret i8 [[TMP0]]
//
int8_t   test_pget_i8x8_i8(int8x8_t v)     { return __riscv_pget_i8x8_i8(v, 5); }
// RV64-LABEL: @test_pget_u8x8_u8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 56
// RV64-NEXT:    [[TMP0:%.*]] = trunc nuw i64 [[EXTELT_OFFSET]] to i8
// RV64-NEXT:    ret i8 [[TMP0]]
//
uint8_t  test_pget_u8x8_u8(uint8x8_t v)    { return __riscv_pget_u8x8_u8(v, 7); }
// RV64-LABEL: @test_pget_i16x4_i16(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 48
// RV64-NEXT:    [[TMP0:%.*]] = trunc nuw i64 [[EXTELT_OFFSET]] to i16
// RV64-NEXT:    ret i16 [[TMP0]]
//
int16_t  test_pget_i16x4_i16(int16x4_t v)  { return __riscv_pget_i16x4_i16(v, 3); }
// RV64-LABEL: @test_pget_u16x4_u16(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 32
// RV64-NEXT:    [[TMP0:%.*]] = trunc i64 [[EXTELT_OFFSET]] to i16
// RV64-NEXT:    ret i16 [[TMP0]]
//
uint16_t test_pget_u16x4_u16(uint16x4_t v) { return __riscv_pget_u16x4_u16(v, 2); }
// RV64-LABEL: @test_pget_i32x2_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[EXTELT_OFFSET:%.*]] = lshr i64 [[V_COERCE:%.*]], 32
// RV64-NEXT:    [[TMP0:%.*]] = trunc nuw i64 [[EXTELT_OFFSET]] to i32
// RV64-NEXT:    ret i32 [[TMP0]]
//
int32_t  test_pget_i32x2_i32(int32x2_t v)  { return __riscv_pget_i32x2_i32(v, 1); }
// RV64-LABEL: @test_pget_u32x2_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = trunc i64 [[V_COERCE:%.*]] to i32
// RV64-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_pget_u32x2_u32(uint32x2_t v) { return __riscv_pget_u32x2_u32(v, 0); }
// RV64-LABEL: @test_pset_i8_i8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[V_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <8 x i8> [[TMP0]], i8 [[E:%.*]], i64 4
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int8x8_t   test_pset_i8_i8x8(int8x8_t v,     int8_t e)   { return __riscv_pset_i8_i8x8(v, e, 4); }
// RV64-LABEL: @test_pset_u8_u8x8(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[V_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <8 x i8> [[TMP0]], i8 [[E:%.*]], i64 6
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint8x8_t  test_pset_u8_u8x8(uint8x8_t v,    uint8_t e)  { return __riscv_pset_u8_u8x8(v, e, 6); }
// RV64-LABEL: @test_pset_i16_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[V_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i16> [[TMP0]], i16 [[E:%.*]], i64 2
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int16x4_t  test_pset_i16_i16x4(int16x4_t v,  int16_t e)  { return __riscv_pset_i16_i16x4(v, e, 2); }
// RV64-LABEL: @test_pset_u16_u16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[V_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <4 x i16> [[TMP0]], i16 [[E:%.*]], i64 3
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint16x4_t test_pset_u16_u16x4(uint16x4_t v, uint16_t e) { return __riscv_pset_u16_u16x4(v, e, 3); }
// RV64-LABEL: @test_pset_i32_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[V_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = insertelement <2 x i32> [[TMP0]], i32 [[E:%.*]], i64 1
// RV64-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32> [[TMP1]] to i64
// RV64-NEXT:    ret i64 [[TMP2]]
//
int32x2_t  test_pset_i32_i32x2(int32x2_t v,  int32_t e)  { return __riscv_pset_i32_i32x2(v, e, 1); }
// RV64-LABEL: @test_pset_u32_u32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = and i64 [[V_COERCE:%.*]], -4294967296
// RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[E:%.*]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = or disjoint i64 [[TMP0]], [[TMP1]]
// RV64-NEXT:    ret i64 [[TMP2]]
//
uint32x2_t test_pset_u32_u32x2(uint32x2_t v, uint32_t e) { return __riscv_pset_u32_u32x2(v, e, 0); }
