// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

// Cross-XLEN forms (mapped to .h.b0 / pmhacc.w.h0 with widening on RV64).
// RV64-LABEL: @test_pmhacc_b0_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP4:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i8> [[TMP4]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT7_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT13_I:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT25_I:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[TMP6:%.*]] = call <4 x i16> @llvm.riscv.pmhacc.b0.v4i16.v8i8(<4 x i16> [[VECINIT7_I]], <4 x i16> [[VECINIT13_I]], <8 x i8> [[VECINIT25_I]])
// RV64-NEXT:    [[VECINIT29_I_BC:%.*]] = bitcast <4 x i16> [[TMP6]] to <2 x i32>
// RV64-NEXT:    [[VECINIT29_I_EXTRACT:%.*]] = extractelement <2 x i32> [[VECINIT29_I_BC]], i64 0
// RV64-NEXT:    ret i32 [[VECINIT29_I_EXTRACT]]
//
int16x2_t test_pmhacc_b0_i16x2(int16x2_t rd, int16x2_t rs1, int8x4_t rs2) {
  return __riscv_pmhacc_b0_i16x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmhaccsu_b1_i16x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RD_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i32 [[RS1_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[TMP4:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <4 x i8>
// RV64-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i8> [[TMP4]], <4 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT7_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT13_I:%.*]] = shufflevector <4 x i16> [[TMP3]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[VECINIT25_I:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> <i8 poison, i8 poison, i8 poison, i8 poison, i8 0, i8 0, i8 0, i8 0>, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 12, i32 13, i32 14, i32 15>
// RV64-NEXT:    [[TMP6:%.*]] = call <4 x i16> @llvm.riscv.pmhaccsu.b1.v4i16.v8i8(<4 x i16> [[VECINIT7_I]], <4 x i16> [[VECINIT13_I]], <8 x i8> [[VECINIT25_I]])
// RV64-NEXT:    [[VECINIT29_I_BC:%.*]] = bitcast <4 x i16> [[TMP6]] to <2 x i32>
// RV64-NEXT:    [[VECINIT29_I_EXTRACT:%.*]] = extractelement <2 x i32> [[VECINIT29_I_BC]], i64 0
// RV64-NEXT:    ret i32 [[VECINIT29_I_EXTRACT]]
//
int16x2_t test_pmhaccsu_b1_i16x2(int16x2_t rd, int16x2_t rs1, uint8x4_t rs2) {
  return __riscv_pmhaccsu_b1_i16x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_mhacc_h0_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT2_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RD:%.*]], i64 0
// RV64-NEXT:    [[VECINIT4_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RS1:%.*]], i64 0
// RV64-NEXT:    [[VECINIT9_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmhacc.h0.v2i32.v4i16(<2 x i32> [[VECINIT2_I]], <2 x i32> [[VECINIT4_I]], <4 x i16> [[VECINIT9_I]])
// RV64-NEXT:    [[VECEXT10_I:%.*]] = extractelement <2 x i32> [[TMP2]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT10_I]]
//
int32_t test_mhacc_h0_i32(int32_t rd, int32_t rs1, int16x2_t rs2) {
  return __riscv_mhacc_h0_i32(rd, rs1, rs2);
}
// RV64-LABEL: @test_mhaccsu_h1_i32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i32 [[RS2_COERCE:%.*]] to <2 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = shufflevector <2 x i16> [[TMP0]], <2 x i16> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
// RV64-NEXT:    [[VECINIT2_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RD:%.*]], i64 0
// RV64-NEXT:    [[VECINIT4_I:%.*]] = insertelement <2 x i32> <i32 poison, i32 0>, i32 [[RS1:%.*]], i64 0
// RV64-NEXT:    [[VECINIT9_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> <i16 poison, i16 poison, i16 0, i16 0>, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
// RV64-NEXT:    [[TMP2:%.*]] = call <2 x i32> @llvm.riscv.pmhaccsu.h1.v2i32.v4i16(<2 x i32> [[VECINIT2_I]], <2 x i32> [[VECINIT4_I]], <4 x i16> [[VECINIT9_I]])
// RV64-NEXT:    [[VECEXT10_I:%.*]] = extractelement <2 x i32> [[TMP2]], i64 0
// RV64-NEXT:    ret i32 [[VECEXT10_I]]
//
int32_t test_mhaccsu_h1_i32(int32_t rd, int32_t rs1, uint16x2_t rs2) {
  return __riscv_mhaccsu_h1_i32(rd, rs1, rs2);
}

// Byte-lane form (RV64 only).
// RV64-LABEL: @test_pmhacc_b0_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = call <4 x i16> @llvm.riscv.pmhacc.b0.v4i16.v8i8(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <8 x i8> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int16x4_t test_pmhacc_b0_i16x4(int16x4_t rd, int16x4_t rs1, int8x8_t rs2) {
  return __riscv_pmhacc_b0_i16x4(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmhacc_b1_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = call <4 x i16> @llvm.riscv.pmhacc.b1.v4i16.v8i8(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <8 x i8> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int16x4_t test_pmhacc_b1_i16x4(int16x4_t rd, int16x4_t rs1, int8x8_t rs2) {
  return __riscv_pmhacc_b1_i16x4(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmhaccsu_b0_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = call <4 x i16> @llvm.riscv.pmhaccsu.b0.v4i16.v8i8(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <8 x i8> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int16x4_t test_pmhaccsu_b0_i16x4(int16x4_t rd, int16x4_t rs1, uint8x8_t rs2) {
  return __riscv_pmhaccsu_b0_i16x4(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmhaccsu_b1_i16x4(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <8 x i8>
// RV64-NEXT:    [[TMP3:%.*]] = call <4 x i16> @llvm.riscv.pmhaccsu.b1.v4i16.v8i8(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <8 x i8> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int16x4_t test_pmhaccsu_b1_i16x4(int16x4_t rd, int16x4_t rs1, uint8x8_t rs2) {
  return __riscv_pmhaccsu_b1_i16x4(rd, rs1, rs2);
}

// Halfword-lane vector form (RV64 only, pmhacc.w.h*).
// RV64-LABEL: @test_pmhacc_h0_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmhacc.h0.v2i32.v4i16(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmhacc_h0_i32x2(int32x2_t rd, int32x2_t rs1, int16x4_t rs2) {
  return __riscv_pmhacc_h0_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmhacc_h1_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmhacc.h1.v2i32.v4i16(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmhacc_h1_i32x2(int32x2_t rd, int32x2_t rs1, int16x4_t rs2) {
  return __riscv_pmhacc_h1_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmhaccsu_h0_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmhaccsu.h0.v2i32.v4i16(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmhaccsu_h0_i32x2(int32x2_t rd, int32x2_t rs1, uint16x4_t rs2) {
  return __riscv_pmhaccsu_h0_i32x2(rd, rs1, rs2);
}
// RV64-LABEL: @test_pmhaccsu_h1_i32x2(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = bitcast i64 [[RD_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP1:%.*]] = bitcast i64 [[RS1_COERCE:%.*]] to <2 x i32>
// RV64-NEXT:    [[TMP2:%.*]] = bitcast i64 [[RS2_COERCE:%.*]] to <4 x i16>
// RV64-NEXT:    [[TMP3:%.*]] = call <2 x i32> @llvm.riscv.pmhaccsu.h1.v2i32.v4i16(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <4 x i16> [[TMP2]])
// RV64-NEXT:    [[TMP4:%.*]] = bitcast <2 x i32> [[TMP3]] to i64
// RV64-NEXT:    ret i64 [[TMP4]]
//
int32x2_t test_pmhaccsu_h1_i32x2(int32x2_t rd, int32x2_t rs1, uint16x4_t rs2) {
  return __riscv_pmhaccsu_h1_i32x2(rd, rs1, rs2);
}
