// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +experimental-p \
// RUN:   -disable-O0-optnone -emit-llvm -o - %s \
// RUN: | opt -S -passes=sroa,instcombine | FileCheck %s --check-prefix=RV64

#include <riscv_packed.h>

/* Common */
// RV64-LABEL: @test_abs_u32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.abs.i32(i32 [[X:%.*]], i1 true)
// RV64-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_abs_u32(int32_t x) { return __riscv_abs_u32(x); }
// RV64-LABEL: @test_cls_32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[X_LOBIT:%.*]] = ashr i32 [[X:%.*]], 31
// RV64-NEXT:    [[TMP0:%.*]] = xor i32 [[X]], [[X_LOBIT]]
// RV64-NEXT:    [[TMP1:%.*]] = call range(i32 0, 33) i32 @llvm.ctlz.i32(i32 [[TMP0]], i1 false)
// RV64-NEXT:    [[TMP2:%.*]] = add nsw i32 [[TMP1]], -1
// RV64-NEXT:    ret i32 [[TMP2]]
//
unsigned test_cls_32(int32_t x)  { return __riscv_cls_32(x); }
// RV64-LABEL: @test_rev_32(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i32 @llvm.bitreverse.i32(i32 [[X:%.*]])
// RV64-NEXT:    ret i32 [[TMP0]]
//
uint32_t test_rev_32(uint32_t x) { return __riscv_rev_32(x); }

/* RV64 only */
// RV64-LABEL: @test_abs_u64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.abs.i64(i64 [[X:%.*]], i1 true)
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_abs_u64(int64_t x) { return __riscv_abs_u64(x); }
// RV64-LABEL: @test_cls_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[X_LOBIT:%.*]] = ashr i64 [[X:%.*]], 63
// RV64-NEXT:    [[TMP0:%.*]] = xor i64 [[X]], [[X_LOBIT]]
// RV64-NEXT:    [[TMP1:%.*]] = call range(i64 0, 65) i64 @llvm.ctlz.i64(i64 [[TMP0]], i1 false)
// RV64-NEXT:    [[TMP2:%.*]] = trunc nuw nsw i64 [[TMP1]] to i32
// RV64-NEXT:    [[CAST_I:%.*]] = add nsw i32 [[TMP2]], -1
// RV64-NEXT:    ret i32 [[CAST_I]]
//
unsigned test_cls_64(int64_t x)  { return __riscv_cls_64(x); }
// RV64-LABEL: @test_rev_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.bitreverse.i64(i64 [[X:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test_rev_64(uint64_t x) { return __riscv_rev_64(x); }
