; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <2 x i16> @llvm.riscv.pmhacc.b0.v2i16.v4i8(<2 x i16>, <2 x i16>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmhacc.b1.v2i16.v4i8(<2 x i16>, <2 x i16>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmhaccsu.b0.v2i16.v4i8(<2 x i16>, <2 x i16>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmhaccsu.b1.v2i16.v4i8(<2 x i16>, <2 x i16>, <4 x i8>)

declare i32 @llvm.riscv.pmhacc.h0.i32.v2i16(i32, i32, <2 x i16>)
declare i32 @llvm.riscv.pmhacc.h1.i32.v2i16(i32, i32, <2 x i16>)
declare i32 @llvm.riscv.pmhaccsu.h0.i32.v2i16(i32, i32, <2 x i16>)
declare i32 @llvm.riscv.pmhaccsu.h1.i32.v2i16(i32, i32, <2 x i16>)

define <2 x i16> @pmhacc_h_b0(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmhacc_h_b0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmhacc.h.b0 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmhacc.b0.v2i16.v4i8(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmhacc_h_b1(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmhacc_h_b1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmhacc.h.b1 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmhacc.b1.v2i16.v4i8(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmhaccsu_h_b0(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmhaccsu_h_b0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmhaccsu.h.b0 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmhaccsu.b0.v2i16.v4i8(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmhaccsu_h_b1(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmhaccsu_h_b1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmhaccsu.h.b1 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmhaccsu.b1.v2i16.v4i8(<2 x i16> %rd, <2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}

define i32 @mhacc_h0(i32 %rd, i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mhacc_h0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mhacc.h0 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmhacc.h0.i32.v2i16(i32 %rd, i32 %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mhacc_h1(i32 %rd, i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mhacc_h1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mhacc.h1 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmhacc.h1.i32.v2i16(i32 %rd, i32 %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mhaccsu_h0(i32 %rd, i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mhaccsu_h0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mhaccsu.h0 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmhaccsu.h0.i32.v2i16(i32 %rd, i32 %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mhaccsu_h1(i32 %rd, i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mhaccsu_h1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mhaccsu.h1 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmhaccsu.h1.i32.v2i16(i32 %rd, i32 %a, <2 x i16> %b)
  ret i32 %r
}
