; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <8 x i8>  @llvm.riscv.pnzip.v8i8.v4i16 (<4 x i16>, <4 x i16>)
declare <8 x i8>  @llvm.riscv.pnziph.v8i8.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.pnzip.v4i16.v2i32 (<2 x i32>, <2 x i32>)
declare <4 x i16> @llvm.riscv.pnziph.v4i16.v2i32(<2 x i32>, <2 x i32>)
declare <4 x i16> @llvm.riscv.psext.h.b.v4i16.v8i8(<8 x i8>)
declare <2 x i32> @llvm.riscv.psext.w.h(<4 x i16>)

define <8 x i8> @pnzip_b(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pnzip_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppaire.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.pnzip.v8i8.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <8 x i8> %r
}

define <8 x i8> @pnziph_b(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pnziph_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairo.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.pnziph.v8i8.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <8 x i8> %r
}

define <4 x i16> @pnzip_h(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pnzip_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppaire.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pnzip.v4i16.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <4 x i16> %r
}

define <4 x i16> @pnziph_h(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pnziph_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairo.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pnziph.v4i16.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <4 x i16> %r
}

define <4 x i16> @psext_h_b(<8 x i8> %a) {
; RV64P-LABEL: psext_h_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psext.h.b a0, a0
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.psext.h.b.v4i16.v8i8(<8 x i8> %a)
  ret <4 x i16> %r
}

define <2 x i32> @psext_w_h(<4 x i16> %a) {
; RV64P-LABEL: psext_w_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psext.w.h a0, a0
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.psext.w.h(<4 x i16> %a)
  ret <2 x i32> %r
}
