; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i32 @llvm.riscv.pm4add.i32.v4i8(<4 x i8>, <4 x i8>)
declare i32 @llvm.riscv.pm4adda.i32.v4i8(i32, <4 x i8>, <4 x i8>)
declare i32 @llvm.riscv.pm4addu.i32.v4i8(<4 x i8>, <4 x i8>)
declare i32 @llvm.riscv.pm4addau.i32.v4i8(i32, <4 x i8>, <4 x i8>)
declare i32 @llvm.riscv.pm4addsu.i32.v4i8(<4 x i8>, <4 x i8>)
declare i32 @llvm.riscv.pm4addasu.i32.v4i8(i32, <4 x i8>, <4 x i8>)

declare i32 @llvm.riscv.pm2add.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2adda.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2add.x.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2adda.x.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2addu.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2addau.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2addsu.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2addasu.i32.v2i16(i32, <2 x i16>, <2 x i16>)

declare i32 @llvm.riscv.pmq2add.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmqr2add.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmq2adda.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmqr2adda.i32.v2i16(i32, <2 x i16>, <2 x i16>)

declare i32 @llvm.riscv.pm2sadd.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2sadd.x.i32.v2i16(<2 x i16>, <2 x i16>)

declare i32 @llvm.riscv.pm2sub.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2suba.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2sub.x.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pm2suba.x.i32.v2i16(i32, <2 x i16>, <2 x i16>)

define i32 @pm4add_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pm4add_b:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm4add.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm4add.i32.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i32 %r
}

define i32 @pm4adda_b(i32 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pm4adda_b:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm4adda.b a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm4adda.i32.v4i8(i32 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i32 %r
}

define i32 @pm4addu_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pm4addu_b:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm4addu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm4addu.i32.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i32 %r
}

define i32 @pm4addau_b(i32 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pm4addau_b:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm4addau.b a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm4addau.i32.v4i8(i32 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i32 %r
}

define i32 @pm4addsu_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pm4addsu_b:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm4addsu.b a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm4addsu.i32.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i32 %r
}

define i32 @pm4addasu_b(i32 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pm4addasu_b:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm4addasu.b a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm4addasu.i32.v4i8(i32 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i32 %r
}

define i32 @pm2add_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2add_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2add.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2add.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2adda_h(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2adda_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2adda.h a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2adda.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2add_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2add_hx:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2add.hx a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2add.x.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2adda_hx(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2adda_hx:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2adda.hx a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2adda.x.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2addu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2addu_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2addu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2addu.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2addau_h(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2addau_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2addau.h a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2addau.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2addsu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2addsu_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2addsu.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2addsu.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2addasu_h(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2addasu_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2addasu.h a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2addasu.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pmq2add_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmq2add_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pmq2add.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pmq2add.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pmqr2add_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmqr2add_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pmqr2add.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pmqr2add.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pmq2adda_h(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmq2adda_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pmq2adda.h a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pmq2adda.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pmqr2adda_h(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmqr2adda_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pmqr2adda.h a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pmqr2adda.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2sadd_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2sadd_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2sadd.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2sadd.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2sadd_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2sadd_hx:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2sadd.hx a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2sadd.x.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2sub_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2sub_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2sub.h a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2sub.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2suba_h(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2suba_h:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2suba.h a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2suba.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2sub_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2sub_hx:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2sub.hx a0, a0, a1
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2sub.x.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}

define i32 @pm2suba_hx(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2suba_hx:
; RV32P:       # %bb.0: # %entry
; RV32P-NEXT:    pm2suba.hx a0, a1, a2
; RV32P-NEXT:    ret
entry:
  %r = call i32 @llvm.riscv.pm2suba.x.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
