; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pwmacc.v2i16(i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwmaccu.v2i16(i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwmaccsu.v2i16(i64, <2 x i16>, <2 x i16>)

define i64 @pwmacc_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwmacc_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmacc.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmacc.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwmaccu_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwmaccu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmaccu.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmaccu.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwmaccsu_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwmaccsu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmaccsu.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmaccsu.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
