; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p,+m,+zbb \
; RUN:   -verify-machineinstrs < %s | \
; RUN:   FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p,+m,+zbb \
; RUN:   -verify-machineinstrs < %s | \
; RUN:   FileCheck %s --check-prefixes=CHECK,RV64

declare <2 x i16> @llvm.riscv.pssha.v2i16(<2 x i16>, i32)
declare <4 x i16> @llvm.riscv.pssha.v4i16(<4 x i16>, i32)
declare <2 x i32> @llvm.riscv.pssha.v2i32(<2 x i32>, i32)
declare <2 x i16> @llvm.riscv.psshar.v2i16(<2 x i16>, i32)
declare <4 x i16> @llvm.riscv.psshar.v4i16(<4 x i16>, i32)
declare <2 x i32> @llvm.riscv.psshar.v2i32(<2 x i32>, i32)
declare <2 x i16> @llvm.riscv.psshl.v2i16(<2 x i16>, i32)
declare <4 x i16> @llvm.riscv.psshl.v4i16(<4 x i16>, i32)
declare <2 x i32> @llvm.riscv.psshl.v2i32(<2 x i32>, i32)
declare <2 x i16> @llvm.riscv.psshlr.v2i16(<2 x i16>, i32)
declare <4 x i16> @llvm.riscv.psshlr.v4i16(<4 x i16>, i32)
declare <2 x i32> @llvm.riscv.psshlr.v2i32(<2 x i32>, i32)

define <2 x i16> @test_pssha_v2i16(<2 x i16> %a, i32 %n) {
; RV32-LABEL: test_pssha_v2i16:
; RV32:       # %bb.0:
; RV32-NEXT:    pssha.hs a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: test_pssha_v2i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    pssha.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pssha.v2i16(<2 x i16> %a, i32 %n)
  ret <2 x i16> %r
}

define <4 x i16> @test_pssha_v4i16(<4 x i16> %a, i32 %n) {
; RV32-LABEL: test_pssha_v4i16:
; RV32:       # %bb.0:
; RV32-NEXT:    pssha.dhs a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_pssha_v4i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    pssha.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pssha.v4i16(<4 x i16> %a, i32 %n)
  ret <4 x i16> %r
}

define <2 x i32> @test_pssha_v2i32(<2 x i32> %a, i32 %n) {
; RV32-LABEL: test_pssha_v2i32:
; RV32:       # %bb.0:
; RV32-NEXT:    pssha.dws a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_pssha_v2i32:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    pssha.ws a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pssha.v2i32(<2 x i32> %a, i32 %n)
  ret <2 x i32> %r
}

define <2 x i16> @test_psshar_v2i16(<2 x i16> %a, i32 %n) {
; RV32-LABEL: test_psshar_v2i16:
; RV32:       # %bb.0:
; RV32-NEXT:    psshar.hs a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshar_v2i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshar.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psshar.v2i16(<2 x i16> %a, i32 %n)
  ret <2 x i16> %r
}

define <4 x i16> @test_psshar_v4i16(<4 x i16> %a, i32 %n) {
; RV32-LABEL: test_psshar_v4i16:
; RV32:       # %bb.0:
; RV32-NEXT:    psshar.dhs a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshar_v4i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshar.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.psshar.v4i16(<4 x i16> %a, i32 %n)
  ret <4 x i16> %r
}

define <2 x i32> @test_psshar_v2i32(<2 x i32> %a, i32 %n) {
; RV32-LABEL: test_psshar_v2i32:
; RV32:       # %bb.0:
; RV32-NEXT:    psshar.dws a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshar_v2i32:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshar.ws a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.psshar.v2i32(<2 x i32> %a, i32 %n)
  ret <2 x i32> %r
}

define <2 x i16> @test_psshl_v2i16(<2 x i16> %a, i32 %n) {
; RV32-LABEL: test_psshl_v2i16:
; RV32:       # %bb.0:
; RV32-NEXT:    psshl.hs a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshl_v2i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshl.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psshl.v2i16(<2 x i16> %a, i32 %n)
  ret <2 x i16> %r
}

define <4 x i16> @test_psshl_v4i16(<4 x i16> %a, i32 %n) {
; RV32-LABEL: test_psshl_v4i16:
; RV32:       # %bb.0:
; RV32-NEXT:    psshl.dhs a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshl_v4i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshl.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.psshl.v4i16(<4 x i16> %a, i32 %n)
  ret <4 x i16> %r
}

define <2 x i32> @test_psshl_v2i32(<2 x i32> %a, i32 %n) {
; RV32-LABEL: test_psshl_v2i32:
; RV32:       # %bb.0:
; RV32-NEXT:    psshl.dws a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshl_v2i32:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshl.ws a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.psshl.v2i32(<2 x i32> %a, i32 %n)
  ret <2 x i32> %r
}

define <2 x i16> @test_psshlr_v2i16(<2 x i16> %a, i32 %n) {
; RV32-LABEL: test_psshlr_v2i16:
; RV32:       # %bb.0:
; RV32-NEXT:    psshlr.hs a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshlr_v2i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshlr.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psshlr.v2i16(<2 x i16> %a, i32 %n)
  ret <2 x i16> %r
}

define <4 x i16> @test_psshlr_v4i16(<4 x i16> %a, i32 %n) {
; RV32-LABEL: test_psshlr_v4i16:
; RV32:       # %bb.0:
; RV32-NEXT:    psshlr.dhs a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshlr_v4i16:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshlr.hs a0, a0, a1
; RV64-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.psshlr.v4i16(<4 x i16> %a, i32 %n)
  ret <4 x i16> %r
}

define <2 x i32> @test_psshlr_v2i32(<2 x i32> %a, i32 %n) {
; RV32-LABEL: test_psshlr_v2i32:
; RV32:       # %bb.0:
; RV32-NEXT:    psshlr.dws a0, a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: test_psshlr_v2i32:
; RV64:       # %bb.0:
; RV64-NEXT:    sext.w a1, a1
; RV64-NEXT:    psshlr.ws a0, a0, a1
; RV64-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.psshlr.v2i32(<2 x i32> %a, i32 %n)
  ret <2 x i32> %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
