; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <2 x i32> @llvm.riscv.pmqacc.h00.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmqacc.h01.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmqacc.h11.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmqracc.h00.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmqracc.h01.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmqracc.h11.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)

declare i64 @llvm.riscv.pmqacc.w00.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmqacc.w01.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmqacc.w11.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmqracc.w00.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmqracc.w01.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmqracc.w11.i64.v2i32(i64, <2 x i32>, <2 x i32>)

define <2 x i32> @pmqacc_w_h00(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqacc_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmqacc.w.h00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmqacc.h00.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmqacc_w_h01(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqacc_w_h01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmqacc.w.h01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmqacc.h01.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmqacc_w_h11(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqacc_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmqacc.w.h11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmqacc.h11.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmqracc_w_h00(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqracc_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmqracc.w.h00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmqracc.h00.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmqracc_w_h01(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqracc_w_h01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmqracc.w.h01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmqracc.h01.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmqracc_w_h11(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqracc_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmqracc.w.h11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmqracc.h11.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define i64 @mqacc_w00(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mqacc_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mqacc.w00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqacc.w00.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mqacc_w01(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mqacc_w01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mqacc.w01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqacc.w01.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mqacc_w11(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mqacc_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mqacc.w11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqacc.w11.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mqracc_w00(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mqracc_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mqracc.w00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqracc.w00.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mqracc_w01(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mqracc_w01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mqracc.w01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqracc.w01.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mqracc_w11(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mqracc_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mqracc.w11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqracc.w11.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
