; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <2 x i16> @llvm.riscv.pas.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.psa.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.psas.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pssa.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.paas.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pasa.x.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pas_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pas_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pas.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pas.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @psa_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: psa_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    psa.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psa.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @psas_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: psas_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    psas.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psas.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pssa_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pssa_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pssa.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pssa.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @paas_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: paas_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    paas.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.paas.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pasa_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pasa_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pasa.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pasa.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}
