; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <4 x i16> @llvm.riscv.pmul.b00.v4i16.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmul.b01.v4i16.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmul.b11.v4i16.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulu.b00.v4i16.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulu.b01.v4i16.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulu.b11.v4i16.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulsu.b00.v4i16.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulsu.b11.v4i16.v8i8(<8 x i8>, <8 x i8>)

declare <2 x i32> @llvm.riscv.pmul.h00.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmul.h01.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmul.h11.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulu.h00.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulu.h01.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulu.h11.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulsu.h00.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulsu.h11.v2i32.v4i16(<4 x i16>, <4 x i16>)

declare i64 @llvm.riscv.pmul.w00.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmul.w01.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmul.w11.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmulu.w00.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmulu.w01.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmulu.w11.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmulsu.w00.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmulsu.w11.i64.v2i32(<2 x i32>, <2 x i32>)

define <4 x i16> @pmul_h_b00(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmul_h_b00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmul.h.b00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmul.b00.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmul_h_b01(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmul_h_b01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmul.h.b01 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmul.b01.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmul_h_b11(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmul_h_b11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmul.h.b11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmul.b11.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulu_h_b00(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulu_h_b00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulu.h.b00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulu.b00.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulu_h_b01(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulu_h_b01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulu.h.b01 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulu.b01.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulu_h_b11(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulu_h_b11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulu.h.b11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulu.b11.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulsu_h_b00(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulsu_h_b00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulsu.h.b00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulsu.b00.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulsu_h_b11(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulsu_h_b11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulsu.h.b11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulsu.b11.v4i16.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <4 x i16> %r
}

define <2 x i32> @pmul_w_h00(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmul_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmul.w.h00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmul.h00.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmul_w_h01(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmul_w_h01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmul.w.h01 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmul.h01.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmul_w_h11(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmul_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmul.w.h11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmul.h11.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulu_w_h00(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulu_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulu.w.h00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulu.h00.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulu_w_h01(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulu_w_h01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulu.w.h01 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulu.h01.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulu_w_h11(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulu_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulu.w.h11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulu.h11.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulsu_w_h00(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulsu_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulsu.w.h00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulsu.h00.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulsu_w_h11(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulsu_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulsu.w.h11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulsu.h11.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define i64 @mul_w00(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mul_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mul.w00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmul.w00.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mul_w01(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mul_w01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mul.w01 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmul.w01.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mul_w11(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mul_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mul.w11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmul.w11.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mulu_w00(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mulu_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mulu.w00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmulu.w00.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mulu_w01(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mulu_w01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mulu.w01 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmulu.w01.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mulu_w11(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mulu_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mulu.w11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmulu.w11.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mulsu_w00(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mulsu_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mulsu.w00 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmulsu.w00.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @mulsu_w11(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: mulsu_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    mulsu.w11 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmulsu.w11.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
