; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

; ----- pm4add family with v8i8 input (output is <2 x i32>) -----

declare <2 x i32> @llvm.riscv.pm4add.v2i32.v8i8(<8 x i8>, <8 x i8>)
declare <2 x i32> @llvm.riscv.pm4adda.v2i32.v8i8(<2 x i32>, <8 x i8>, <8 x i8>)
declare <2 x i32> @llvm.riscv.pm4addu.v2i32.v8i8(<8 x i8>, <8 x i8>)
declare <2 x i32> @llvm.riscv.pm4addau.v2i32.v8i8(<2 x i32>, <8 x i8>, <8 x i8>)
declare <2 x i32> @llvm.riscv.pm4addsu.v2i32.v8i8(<8 x i8>, <8 x i8>)
declare <2 x i32> @llvm.riscv.pm4addasu.v2i32.v8i8(<2 x i32>, <8 x i8>, <8 x i8>)

; ----- pm4add family with v4i16 input (output is i64 scalar) -----

declare i64 @llvm.riscv.pm4add.i64.v4i16(<4 x i16>, <4 x i16>)
declare i64 @llvm.riscv.pm4adda.i64.v4i16(i64, <4 x i16>, <4 x i16>)
declare i64 @llvm.riscv.pm4addu.i64.v4i16(<4 x i16>, <4 x i16>)
declare i64 @llvm.riscv.pm4addau.i64.v4i16(i64, <4 x i16>, <4 x i16>)
declare i64 @llvm.riscv.pm4addsu.i64.v4i16(<4 x i16>, <4 x i16>)
declare i64 @llvm.riscv.pm4addasu.i64.v4i16(i64, <4 x i16>, <4 x i16>)

; ----- pm2add family with v4i16 input (output is <2 x i32>) -----

declare <2 x i32> @llvm.riscv.pm2add.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2adda.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2add.x.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2adda.x.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2addu.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2addau.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2addsu.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2addasu.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)

; ----- pm2add family with v2i32 input (output is i64 scalar) -----

declare i64 @llvm.riscv.pm2add.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2adda.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2add.x.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2adda.x.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2addu.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2addau.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2addsu.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2addasu.i64.v2i32(i64, <2 x i32>, <2 x i32>)

; ----- Q-format intrinsics -----

declare <2 x i32> @llvm.riscv.pmq2add.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmqr2add.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmq2adda.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmqr2adda.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare i64 @llvm.riscv.pmq2add.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmqr2add.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmq2adda.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmqr2adda.i64.v2i32(i64, <2 x i32>, <2 x i32>)

; ----- Saturating multiply-add (no accumulator) -----

declare <2 x i32> @llvm.riscv.pm2sadd.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2sadd.x.v2i32.v4i16(<4 x i16>, <4 x i16>)

; ----- Multiply-subtract -----

declare <2 x i32> @llvm.riscv.pm2sub.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2suba.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2sub.x.v2i32.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pm2suba.x.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare i64 @llvm.riscv.pm2sub.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2suba.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2sub.x.i64.v2i32(<2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pm2suba.x.i64.v2i32(i64, <2 x i32>, <2 x i32>)

; ----- Tests: pm4add byte (v8i8 -> v2i32) -----

define <2 x i32> @pm4add_b_8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pm4add_b_8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4add.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm4add.v2i32.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm4adda_b_8x8(<2 x i32> %rd, <8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pm4adda_b_8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4adda.b a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm4adda.v2i32.v8i8(<2 x i32> %rd, <8 x i8> %a, <8 x i8> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm4addu_b_8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pm4addu_b_8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addu.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm4addu.v2i32.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm4addau_b_8x8(<2 x i32> %rd, <8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pm4addau_b_8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addau.b a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm4addau.v2i32.v8i8(<2 x i32> %rd, <8 x i8> %a, <8 x i8> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm4addsu_b_8x8(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pm4addsu_b_8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addsu.b a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm4addsu.v2i32.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm4addasu_b_8x8(<2 x i32> %rd, <8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pm4addasu_b_8x8:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addasu.b a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm4addasu.v2i32.v8i8(<2 x i32> %rd, <8 x i8> %a, <8 x i8> %b)
  ret <2 x i32> %r
}

; ----- Tests: pm4add halfword (v4i16 -> i64) -----

define i64 @pm4add_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm4add_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4add.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm4add.i64.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret i64 %r
}

define i64 @pm4adda_h(i64 %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm4adda_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4adda.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm4adda.i64.v4i16(i64 %rd, <4 x i16> %a, <4 x i16> %b)
  ret i64 %r
}

define i64 @pm4addu_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm4addu_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm4addu.i64.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret i64 %r
}

define i64 @pm4addau_h(i64 %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm4addau_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addau.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm4addau.i64.v4i16(i64 %rd, <4 x i16> %a, <4 x i16> %b)
  ret i64 %r
}

define i64 @pm4addsu_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm4addsu_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addsu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm4addsu.i64.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret i64 %r
}

define i64 @pm4addasu_h(i64 %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm4addasu_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm4addasu.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm4addasu.i64.v4i16(i64 %rd, <4 x i16> %a, <4 x i16> %b)
  ret i64 %r
}

; ----- Tests: pm2add halfword (v4i16 -> v2i32) -----

define <2 x i32> @pm2add_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2add_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2add.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2add.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2adda_h(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2adda_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2adda.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2adda.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2add_hx(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2add_hx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2add.hx a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2add.x.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2adda_hx(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2adda_hx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2adda.hx a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2adda.x.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2addu_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2addu_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2addu.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2addau_h(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2addau_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addau.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2addau.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2addsu_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2addsu_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addsu.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2addsu.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2addasu_h(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2addasu_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addasu.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2addasu.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

; ----- Tests: pm2add word (v2i32 -> i64) -----

define i64 @pm2add_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2add_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2add.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2add.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2adda_w(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2adda_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2adda.w a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2adda.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2add_wx(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2add_wx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2add.wx a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2add.x.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2adda_wx(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2adda_wx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2adda.wx a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2adda.x.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2addu_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2addu_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addu.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2addu.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2addau_w(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2addau_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addau.w a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2addau.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2addsu_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2addsu_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addsu.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2addsu.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2addasu_w(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2addasu_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2addasu.w a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2addasu.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

; ----- Tests: Q-format halfword -----

define <2 x i32> @pmq2add_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmq2add_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmq2add.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pmq2add.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pmqr2add_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqr2add_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmqr2add.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pmqr2add.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pmq2adda_h(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmq2adda_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmq2adda.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pmq2adda.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pmqr2adda_h(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmqr2adda_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmqr2adda.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pmqr2adda.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

; ----- Tests: Q-format word -----

define i64 @pmq2add_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmq2add_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmq2add.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pmq2add.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pmqr2add_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmqr2add_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmqr2add.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pmqr2add.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pmq2adda_w(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmq2adda_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmq2adda.w a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pmq2adda.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pmqr2adda_w(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmqr2adda_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pmqr2adda.w a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pmqr2adda.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

; ----- Tests: Saturating halfword -----

define <2 x i32> @pm2sadd_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2sadd_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2sadd.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2sadd.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2sadd_hx(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2sadd_hx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2sadd.hx a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2sadd.x.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

; ----- Tests: Multiply-subtract halfword -----

define <2 x i32> @pm2sub_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2sub_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2sub.h a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2sub.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2suba_h(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2suba_h:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2suba.h a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2suba.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2sub_hx(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2sub_hx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2sub.hx a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2sub.x.v2i32.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pm2suba_hx(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pm2suba_hx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2suba.hx a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call <2 x i32> @llvm.riscv.pm2suba.x.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

; ----- Tests: Multiply-subtract word -----

define i64 @pm2sub_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2sub_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2sub.w a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2sub.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2suba_w(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2suba_w:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2suba.w a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2suba.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2sub_wx(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2sub_wx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2sub.wx a0, a0, a1
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2sub.x.i64.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}

define i64 @pm2suba_wx(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pm2suba_wx:
; RV64P:       # %bb.0: # %entry
; RV64P-NEXT:    pm2suba.wx a0, a1, a2
; RV64P-NEXT:    ret
entry:
  %r = call i64 @llvm.riscv.pm2suba.x.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
