; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <2 x i16> @llvm.riscv.pmulq.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pmulqr.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pmulq_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmulq_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulq.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulq.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pmulqr_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmulqr_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulqr.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulqr.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}
