; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pwsll.v4i8 (<4 x i8>,  i32)
declare i64 @llvm.riscv.pwsll.v2i16(<2 x i16>, i32)
declare i64 @llvm.riscv.pwsla.v4i8 (<4 x i8>,  i32)
declare i64 @llvm.riscv.pwsla.v2i16(<2 x i16>, i32)

define i64 @pwslli_b(<4 x i8> %a) {
; RV32P-LABEL: pwslli_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwslli.b a0, a0, 3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsll.v4i8(<4 x i8> %a, i32 3)
  ret i64 %r
}
define i64 @pwsll_bs(<4 x i8> %a, i32 %s) {
; RV32P-LABEL: pwsll_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsll.bs a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsll.v4i8(<4 x i8> %a, i32 %s)
  ret i64 %r
}
define i64 @pwslli_h(<2 x i16> %a) {
; RV32P-LABEL: pwslli_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwslli.h a0, a0, 7
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsll.v2i16(<2 x i16> %a, i32 7)
  ret i64 %r
}
define i64 @pwsll_hs(<2 x i16> %a, i32 %s) {
; RV32P-LABEL: pwsll_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsll.hs a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsll.v2i16(<2 x i16> %a, i32 %s)
  ret i64 %r
}
define i64 @pwslai_b(<4 x i8> %a) {
; RV32P-LABEL: pwslai_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwslai.b a0, a0, 2
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsla.v4i8(<4 x i8> %a, i32 2)
  ret i64 %r
}
define i64 @pwsla_bs(<4 x i8> %a, i32 %s) {
; RV32P-LABEL: pwsla_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsla.bs a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsla.v4i8(<4 x i8> %a, i32 %s)
  ret i64 %r
}
define i64 @pwslai_h(<2 x i16> %a) {
; RV32P-LABEL: pwslai_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwslai.h a0, a0, 11
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsla.v2i16(<2 x i16> %a, i32 11)
  ret i64 %r
}
define i64 @pwsla_hs(<2 x i16> %a, i32 %s) {
; RV32P-LABEL: pwsla_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsla.hs a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsla.v2i16(<2 x i16> %a, i32 %s)
  ret i64 %r
}
