; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <2 x i16> @llvm.riscv.pmul.b00.v2i16.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmul.b01.v2i16.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmul.b11.v2i16.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulu.b00.v2i16.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulu.b01.v2i16.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulu.b11.v2i16.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulsu.b00.v2i16.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulsu.b11.v2i16.v4i8(<4 x i8>, <4 x i8>)

declare i32 @llvm.riscv.pmul.h00.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmul.h01.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmul.h11.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmulu.h00.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmulu.h01.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmulu.h11.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmulsu.h00.i32.v2i16(<2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmulsu.h11.i32.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @pmul_h_b00(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmul_h_b00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmul.h.b00 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmul.b00.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmul_h_b01(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmul_h_b01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmul.h.b01 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmul.b01.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmul_h_b11(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmul_h_b11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmul.h.b11 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmul.b11.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulu_h_b00(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulu_h_b00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulu.h.b00 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulu.b00.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulu_h_b01(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulu_h_b01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulu.h.b01 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulu.b01.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulu_h_b11(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulu_h_b11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulu.h.b11 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulu.b11.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulsu_h_b00(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulsu_h_b00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulsu.h.b00 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulsu.b00.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulsu_h_b11(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulsu_h_b11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulsu.h.b11 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulsu.b11.v2i16.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <2 x i16> %r
}

define i32 @mul_h00(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mul_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mul.h00 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmul.h00.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mul_h01(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mul_h01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mul.h01 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmul.h01.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mul_h11(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mul_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mul.h11 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmul.h11.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulu_h00(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mulu_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulu.h00 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulu.h00.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulu_h01(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mulu_h01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulu.h01 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulu.h01.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulu_h11(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mulu_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulu.h11 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulu.h11.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulsu_h00(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mulsu_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulsu.h00 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulsu.h00.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulsu_h11(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mulsu_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulsu.h11 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulsu.h11.i32.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
