; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <2 x i16> @llvm.riscv.pmulh.b0.v2i16.v4i8(<2 x i16>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulh.b1.v2i16.v4i8(<2 x i16>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulhsu.b0.v2i16.v4i8(<2 x i16>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmulhsu.b1.v2i16.v4i8(<2 x i16>, <4 x i8>)

declare i32 @llvm.riscv.pmulh.h0.i32.v2i16(i32, <2 x i16>)
declare i32 @llvm.riscv.pmulh.h1.i32.v2i16(i32, <2 x i16>)
declare i32 @llvm.riscv.pmulhsu.h0.i32.v2i16(i32, <2 x i16>)
declare i32 @llvm.riscv.pmulhsu.h1.i32.v2i16(i32, <2 x i16>)

define <2 x i16> @pmulh_h_b0(<2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulh_h_b0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulh.h.b0 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulh.b0.v2i16.v4i8(<2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulh_h_b1(<2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulh_h_b1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulh.h.b1 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulh.b1.v2i16.v4i8(<2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulhsu_h_b0(<2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulhsu_h_b0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulhsu.h.b0 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulhsu.b0.v2i16.v4i8(<2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}
define <2 x i16> @pmulhsu_h_b1(<2 x i16> %a, <4 x i8> %b) {
; RV32P-LABEL: pmulhsu_h_b1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmulhsu.h.b1 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulhsu.b1.v2i16.v4i8(<2 x i16> %a, <4 x i8> %b)
  ret <2 x i16> %r
}

define i32 @mulh_h0(i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mulh_h0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulh.h0 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulh.h0.i32.v2i16(i32 %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulh_h1(i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mulh_h1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulh.h1 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulh.h1.i32.v2i16(i32 %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulhsu_h0(i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mulhsu_h0:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulhsu.h0 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulhsu.h0.i32.v2i16(i32 %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mulhsu_h1(i32 %a, <2 x i16> %b) {
; RV32P-LABEL: mulhsu_h1:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mulhsu.h1 a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmulhsu.h1.i32.v2i16(i32 %a, <2 x i16> %b)
  ret i32 %r
}
