; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <4 x i16> @llvm.riscv.pmulh.b0.v4i16.v8i8(<4 x i16>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulh.b1.v4i16.v8i8(<4 x i16>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulhsu.b0.v4i16.v8i8(<4 x i16>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmulhsu.b1.v4i16.v8i8(<4 x i16>, <8 x i8>)

declare <2 x i32> @llvm.riscv.pmulh.h0.v2i32.v4i16(<2 x i32>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulh.h1.v2i32.v4i16(<2 x i32>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulhsu.h0.v2i32.v4i16(<2 x i32>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulhsu.h1.v2i32.v4i16(<2 x i32>, <4 x i16>)

define <4 x i16> @pmulh_h_b0(<4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulh_h_b0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulh.h.b0 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulh.b0.v4i16.v8i8(<4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulh_h_b1(<4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulh_h_b1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulh.h.b1 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulh.b1.v4i16.v8i8(<4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulhsu_h_b0(<4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulhsu_h_b0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulhsu.h.b0 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulhsu.b0.v4i16.v8i8(<4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmulhsu_h_b1(<4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmulhsu_h_b1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulhsu.h.b1 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulhsu.b1.v4i16.v8i8(<4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}

define <2 x i32> @pmulh_w_h0(<2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulh_w_h0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulh.w.h0 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulh.h0.v2i32.v4i16(<2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulh_w_h1(<2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulh_w_h1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulh.w.h1 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulh.h1.v2i32.v4i16(<2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulhsu_w_h0(<2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulhsu_w_h0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulhsu.w.h0 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulhsu.h0.v2i32.v4i16(<2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmulhsu_w_h1(<2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulhsu_w_h1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulhsu.w.h1 a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulhsu.h1.v2i32.v4i16(<2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
