; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <2 x i16> @llvm.riscv.pas.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.psa.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.psas.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pssa.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.paas.x.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pasa.x.v2i16(<2 x i16>, <2 x i16>)

declare <4 x i16> @llvm.riscv.pas.x.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.psa.x.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.psas.x.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.pssa.x.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.paas.x.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.pasa.x.v4i16(<4 x i16>, <4 x i16>)

declare <2 x i32> @llvm.riscv.pas.x.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.psa.x.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.psas.x.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.pssa.x.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.paas.x.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.pasa.x.v2i32(<2 x i32>, <2 x i32>)

define <2 x i16> @pas_hx_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: pas_hx_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pas.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pas.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @psa_hx_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: psa_hx_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psa.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psa.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @psas_hx_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: psas_hx_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psas.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psas.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pssa_hx_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: pssa_hx_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pssa.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pssa.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @paas_hx_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: paas_hx_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    paas.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.paas.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pasa_hx_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: pasa_hx_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pasa.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pasa.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <4 x i16> @pas_hx_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pas_hx_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pas.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pas.x.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @psa_hx_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: psa_hx_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psa.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.psa.x.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @psas_hx_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: psas_hx_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psas.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.psas.x.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @pssa_hx_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pssa_hx_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pssa.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pssa.x.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @paas_hx_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: paas_hx_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    paas.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.paas.x.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @pasa_hx_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pasa_hx_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pasa.hx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pasa.x.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <2 x i32> @pas_wx_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pas_wx_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pas.wx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pas.x.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @psa_wx_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: psa_wx_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psa.wx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.psa.x.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @psas_wx_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: psas_wx_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psas.wx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.psas.x.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pssa_wx_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pssa_wx_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pssa.wx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pssa.x.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @paas_wx_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: paas_wx_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    paas.wx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.paas.x.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pasa_wx_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pasa_wx_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pasa.wx a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pasa.x.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
