; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

; The 32-bit-table forms (v4i8 / v2i16) are exercised by the RV32 .ll test;
; on RV64 those vector types are not directly legal in a GPR-sized register
; and are reached through the i32-coerced calling convention used by the
; clang builtins.

declare <8 x i8>  @llvm.riscv.pmseq.v8i8 (<8 x i8>, <8 x i8>)
declare <8 x i8>  @llvm.riscv.pmslt.v8i8 (<8 x i8>, <8 x i8>)
declare <8 x i8>  @llvm.riscv.pmsltu.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmseq.v4i16 (<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.pmslt.v4i16 (<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.pmsltu.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmseq.v2i32 (<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.pmslt.v2i32 (<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.pmsltu.v2i32(<2 x i32>, <2 x i32>)

define <8 x i8> @pmseq_b(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmseq_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmseq.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.pmseq.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %r
}

define <8 x i8> @pmslt_b(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmslt_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmslt.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.pmslt.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %r
}

define <8 x i8> @pmsltu_b(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: pmsltu_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmsltu.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.pmsltu.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %r
}

define <4 x i16> @pmseq_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmseq_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmseq.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmseq.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @pmslt_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmslt_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmslt.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmslt.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @pmsltu_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmsltu_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmsltu.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmsltu.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <2 x i32> @pmseq_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmseq_w:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmseq.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmseq.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pmslt_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmslt_w:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmslt.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmslt.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pmsltu_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmsltu_w:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmsltu.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmsltu.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
