; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <2 x i16> @llvm.riscv.psh1add.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pssh1sadd.v2i16(<2 x i16>, <2 x i16>)
declare <4 x i16> @llvm.riscv.psh1add.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.pssh1sadd.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.psh1add.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.pssh1sadd.v2i32(<2 x i32>, <2 x i32>)

define <2 x i16> @psh1add_h_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: psh1add_h_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psh1add.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.psh1add.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pssh1sadd_h_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: pssh1sadd_h_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pssh1sadd.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pssh1sadd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <4 x i16> @psh1add_h_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: psh1add_h_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psh1add.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.psh1add.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @pssh1sadd_h_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pssh1sadd_h_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pssh1sadd.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pssh1sadd.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <2 x i32> @psh1add_w_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: psh1add_w_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    psh1add.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.psh1add.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pssh1sadd_w_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pssh1sadd_w_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pssh1sadd.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pssh1sadd.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
