; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <2 x i16> @llvm.riscv.pmulq.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pmulqr.v2i16(<2 x i16>, <2 x i16>)
declare <4 x i16> @llvm.riscv.pmulq.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.pmulqr.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmulq.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.pmulqr.v2i32(<2 x i32>, <2 x i32>)

define <2 x i16> @pmulq_h_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: pmulq_h_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulq.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulq.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pmulqr_h_h2(<2 x i16> %a, <2 x i16> %b) {
; RV64P-LABEL: pmulqr_h_h2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulqr.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmulqr.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <4 x i16> @pmulq_h_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulq_h_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulq.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulq.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <4 x i16> @pmulqr_h_h4(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmulqr_h_h4:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulqr.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmulqr.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <2 x i32> @pmulq_w_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmulq_w_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulq.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulq.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}

define <2 x i32> @pmulqr_w_w2(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: pmulqr_w_w2:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmulqr.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmulqr.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
