; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pmqwacc.v2i16(i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pmqrwacc.v2i16(i64, <2 x i16>, <2 x i16>)

define i64 @pmqwacc_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmqwacc_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmqwacc.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqwacc.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pmqrwacc_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmqrwacc_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmqrwacc.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmqrwacc.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
