; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <4 x i8>  @llvm.riscv.pnsrl.v4i8 (i64, i32)
declare <2 x i16> @llvm.riscv.pnsrl.v2i16(i64, i32)
declare <4 x i8>  @llvm.riscv.pnsra.v4i8 (i64, i32)
declare <2 x i16> @llvm.riscv.pnsra.v2i16(i64, i32)
declare <4 x i8>  @llvm.riscv.pnsrar.v4i8 (i64, i32)
declare <2 x i16> @llvm.riscv.pnsrar.v2i16(i64, i32)

define <4 x i8> @pnsrli_b(i64 %a) {
; RV32P-LABEL: pnsrli_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrli.b a0, a0, 4
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnsrl.v4i8(i64 %a, i32 4)
  ret <4 x i8> %r
}
define <4 x i8> @pnsrl_bs(i64 %a, i32 %s) {
; RV32P-LABEL: pnsrl_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrl.bs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnsrl.v4i8(i64 %a, i32 %s)
  ret <4 x i8> %r
}
define <2 x i16> @pnsrli_h(i64 %a) {
; RV32P-LABEL: pnsrli_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrli.h a0, a0, 17
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnsrl.v2i16(i64 %a, i32 17)
  ret <2 x i16> %r
}
define <2 x i16> @pnsrl_hs(i64 %a, i32 %s) {
; RV32P-LABEL: pnsrl_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrl.hs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnsrl.v2i16(i64 %a, i32 %s)
  ret <2 x i16> %r
}
define <4 x i8> @pnsrai_b(i64 %a) {
; RV32P-LABEL: pnsrai_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrai.b a0, a0, 5
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnsra.v4i8(i64 %a, i32 5)
  ret <4 x i8> %r
}
define <4 x i8> @pnsra_bs(i64 %a, i32 %s) {
; RV32P-LABEL: pnsra_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsra.bs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnsra.v4i8(i64 %a, i32 %s)
  ret <4 x i8> %r
}
define <2 x i16> @pnsrai_h(i64 %a) {
; RV32P-LABEL: pnsrai_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrai.h a0, a0, 19
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnsra.v2i16(i64 %a, i32 19)
  ret <2 x i16> %r
}
define <2 x i16> @pnsra_hs(i64 %a, i32 %s) {
; RV32P-LABEL: pnsra_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsra.hs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnsra.v2i16(i64 %a, i32 %s)
  ret <2 x i16> %r
}
define <4 x i8> @pnsrari_b(i64 %a) {
; RV32P-LABEL: pnsrari_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrari.b a0, a0, 6
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnsrar.v4i8(i64 %a, i32 6)
  ret <4 x i8> %r
}
define <4 x i8> @pnsrar_bs(i64 %a, i32 %s) {
; RV32P-LABEL: pnsrar_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrar.bs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnsrar.v4i8(i64 %a, i32 %s)
  ret <4 x i8> %r
}
define <2 x i16> @pnsrari_h(i64 %a) {
; RV32P-LABEL: pnsrari_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrari.h a0, a0, 21
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnsrar.v2i16(i64 %a, i32 21)
  ret <2 x i16> %r
}
define <2 x i16> @pnsrar_hs(i64 %a, i32 %s) {
; RV32P-LABEL: pnsrar_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnsrar.hs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnsrar.v2i16(i64 %a, i32 %s)
  ret <2 x i16> %r
}
