; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

; The 32-bit-table forms (v4i8 / v2i16) are exercised by the RV32 .ll test;
; on RV64 those vector types are not directly legal in a GPR-sized register
; and are reached through the i32-coerced calling convention used by the
; clang builtins.

declare <8 x i8>  @llvm.riscv.ppaire.v8i8 (<8 x i8>, <8 x i8>)
declare <8 x i8>  @llvm.riscv.ppaireo.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i8>  @llvm.riscv.ppairoe.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i8>  @llvm.riscv.ppairo.v8i8 (<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.riscv.ppaire.v4i16 (<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.ppaireo.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.ppairoe.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.riscv.ppairo.v4i16 (<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.ppaire.v2i32 (<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.ppaireo.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.ppairoe.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.riscv.ppairo.v2i32 (<2 x i32>, <2 x i32>)

define <8 x i8> @ppaire_b(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: ppaire_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppaire.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.ppaire.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %r
}
define <8 x i8> @ppaireo_b(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: ppaireo_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppaireo.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.ppaireo.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %r
}
define <8 x i8> @ppairoe_b(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: ppairoe_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairoe.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.ppairoe.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %r
}
define <8 x i8> @ppairo_b(<8 x i8> %a, <8 x i8> %b) {
; RV64P-LABEL: ppairo_b:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairo.b a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <8 x i8> @llvm.riscv.ppairo.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %r
}

define <4 x i16> @ppaire_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: ppaire_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppaire.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.ppaire.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}
define <4 x i16> @ppaireo_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: ppaireo_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppaireo.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.ppaireo.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}
define <4 x i16> @ppairoe_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: ppairoe_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairoe.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.ppairoe.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}
define <4 x i16> @ppairo_h(<4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: ppairo_h:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairo.h a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.ppairo.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %r
}

define <2 x i32> @ppaire_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: ppaire_w:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pack a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.ppaire.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
define <2 x i32> @ppaireo_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: ppaireo_w:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppaireo.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.ppaireo.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
define <2 x i32> @ppairoe_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: ppairoe_w:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairoe.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.ppairoe.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
define <2 x i32> @ppairo_w(<2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: ppairo_w:
; RV64P:       # %bb.0:
; RV64P-NEXT:    ppairo.w a0, a0, a1
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.ppairo.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %r
}
