; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i32 @llvm.riscv.pmqacc.h00.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmqacc.h01.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmqacc.h11.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmqracc.h00.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmqracc.h01.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmqracc.h11.i32.v2i16(i32, <2 x i16>, <2 x i16>)

define i32 @mqacc_h00(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mqacc_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mqacc.h00 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmqacc.h00.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mqacc_h01(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mqacc_h01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mqacc.h01 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmqacc.h01.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mqacc_h11(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mqacc_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mqacc.h11 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmqacc.h11.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mqracc_h00(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mqracc_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mqracc.h00 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmqracc.h00.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mqracc_h01(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mqracc_h01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mqracc.h01 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmqracc.h01.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @mqracc_h11(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: mqracc_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    mqracc.h11 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmqracc.h11.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
