; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pwcvt.v4i8 (<4 x i8>)
declare i64 @llvm.riscv.pwcvt.v2i16(<2 x i16>)
declare i64 @llvm.riscv.pwcvtu.v4i8 (<4 x i8>)
declare i64 @llvm.riscv.pwcvtu.v2i16(<2 x i16>)
declare i64 @llvm.riscv.pwcvth.v4i8 (<4 x i8>)
declare i64 @llvm.riscv.pwcvth.v2i16(<2 x i16>)

define i64 @pwcvt_b(<4 x i8> %a) {
; RV32P-LABEL: pwcvt_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwadd.b a0, a0, zero
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwcvt.v4i8(<4 x i8> %a)
  ret i64 %r
}
define i64 @pwcvt_h(<2 x i16> %a) {
; RV32P-LABEL: pwcvt_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwadd.h a0, a0, zero
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwcvt.v2i16(<2 x i16> %a)
  ret i64 %r
}
define i64 @pwcvtu_b(<4 x i8> %a) {
; RV32P-LABEL: pwcvtu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    wzip8p a0, a0, zero
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwcvtu.v4i8(<4 x i8> %a)
  ret i64 %r
}
define i64 @pwcvtu_h(<2 x i16> %a) {
; RV32P-LABEL: pwcvtu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    wzip16p a0, a0, zero
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwcvtu.v2i16(<2 x i16> %a)
  ret i64 %r
}
define i64 @pwcvth_b(<4 x i8> %a) {
; RV32P-LABEL: pwcvth_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    wzip8p a0, zero, a0
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwcvth.v4i8(<4 x i8> %a)
  ret i64 %r
}
define i64 @pwcvth_h(<2 x i16> %a) {
; RV32P-LABEL: pwcvth_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    wzip16p a0, zero, a0
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwcvth.v2i16(<2 x i16> %a)
  ret i64 %r
}
