; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pwmul.v4i8(<4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwmul.v2i16(<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwmulu.v4i8(<4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwmulu.v2i16(<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwmulsu.v4i8(<4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwmulsu.v2i16(<2 x i16>, <2 x i16>)

define i64 @pwmul_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwmul_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmul.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmul.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwmul_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwmul_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmul.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmul.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwmulu_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwmulu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmulu.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmulu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwmulu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwmulu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmulu.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmulu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwmulsu_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwmulsu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmulsu.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmulsu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwmulsu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwmulsu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwmulsu.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwmulsu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
