; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <4 x i8>  @llvm.riscv.pnclipu.v4i8 (i64, i32)
declare <2 x i16> @llvm.riscv.pnclipu.v2i16(i64, i32)
declare <4 x i8>  @llvm.riscv.pnclipru.v4i8 (i64, i32)
declare <2 x i16> @llvm.riscv.pnclipru.v2i16(i64, i32)
declare <4 x i8>  @llvm.riscv.pnclip.v4i8 (i64, i32)
declare <2 x i16> @llvm.riscv.pnclip.v2i16(i64, i32)
declare <4 x i8>  @llvm.riscv.pnclipr.v4i8 (i64, i32)
declare <2 x i16> @llvm.riscv.pnclipr.v2i16(i64, i32)

define <4 x i8> @pnclipiu_b(i64 %a) {
; RV32P-LABEL: pnclipiu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipiu.b a0, a0, 4
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclipu.v4i8(i64 %a, i32 4)
  ret <4 x i8> %r
}
define <4 x i8> @pnclipu_bs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclipu_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipu.bs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclipu.v4i8(i64 %a, i32 %s)
  ret <4 x i8> %r
}
define <2 x i16> @pnclipiu_h(i64 %a) {
; RV32P-LABEL: pnclipiu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipiu.h a0, a0, 17
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclipu.v2i16(i64 %a, i32 17)
  ret <2 x i16> %r
}
define <2 x i16> @pnclipu_hs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclipu_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipu.hs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclipu.v2i16(i64 %a, i32 %s)
  ret <2 x i16> %r
}
define <4 x i8> @pnclipriu_b(i64 %a) {
; RV32P-LABEL: pnclipriu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipriu.b a0, a0, 4
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclipru.v4i8(i64 %a, i32 4)
  ret <4 x i8> %r
}
define <4 x i8> @pnclipru_bs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclipru_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipru.bs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclipru.v4i8(i64 %a, i32 %s)
  ret <4 x i8> %r
}
define <2 x i16> @pnclipriu_h(i64 %a) {
; RV32P-LABEL: pnclipriu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipriu.h a0, a0, 17
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclipru.v2i16(i64 %a, i32 17)
  ret <2 x i16> %r
}
define <2 x i16> @pnclipru_hs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclipru_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipru.hs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclipru.v2i16(i64 %a, i32 %s)
  ret <2 x i16> %r
}
define <4 x i8> @pnclipi_b(i64 %a) {
; RV32P-LABEL: pnclipi_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipi.b a0, a0, 5
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclip.v4i8(i64 %a, i32 5)
  ret <4 x i8> %r
}
define <4 x i8> @pnclip_bs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclip_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclip.bs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclip.v4i8(i64 %a, i32 %s)
  ret <4 x i8> %r
}
define <2 x i16> @pnclipi_h(i64 %a) {
; RV32P-LABEL: pnclipi_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipi.h a0, a0, 19
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclip.v2i16(i64 %a, i32 19)
  ret <2 x i16> %r
}
define <2 x i16> @pnclip_hs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclip_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclip.hs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclip.v2i16(i64 %a, i32 %s)
  ret <2 x i16> %r
}
define <4 x i8> @pnclipri_b(i64 %a) {
; RV32P-LABEL: pnclipri_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipri.b a0, a0, 6
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclipr.v4i8(i64 %a, i32 6)
  ret <4 x i8> %r
}
define <4 x i8> @pnclipr_bs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclipr_bs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipr.bs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pnclipr.v4i8(i64 %a, i32 %s)
  ret <4 x i8> %r
}
define <2 x i16> @pnclipri_h(i64 %a) {
; RV32P-LABEL: pnclipri_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipri.h a0, a0, 21
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclipr.v2i16(i64 %a, i32 21)
  ret <2 x i16> %r
}
define <2 x i16> @pnclipr_hs(i64 %a, i32 %s) {
; RV32P-LABEL: pnclipr_hs:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pnclipr.hs a0, a0, a2
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pnclipr.v2i16(i64 %a, i32 %s)
  ret <2 x i16> %r
}
