; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pwadd.v4i8(<4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwadd.v2i16(<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwaddu.v4i8(<4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwaddu.v2i16(<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwsub.v4i8(<4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwsub.v2i16(<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwsubu.v4i8(<4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwsubu.v2i16(<2 x i16>, <2 x i16>)

define i64 @pwadd_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwadd_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwadd.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwadd.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwadd_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwadd_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwadd.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwadd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwaddu_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwaddu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwaddu.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwaddu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwaddu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwaddu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwaddu.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwaddu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwsub_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwsub_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsub.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsub.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwsub_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwsub_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsub.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsub.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwsubu_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwsubu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsubu.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsubu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwsubu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwsubu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsubu.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsubu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
