; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pzip.v4i8 (<4 x i8>,  <4 x i8>)
declare i64 @llvm.riscv.pzip.v2i16(<2 x i16>, <2 x i16>)

define i64 @pzip_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pzip_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    wzip8p a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pzip.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pzip_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pzip_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    wzip16p a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pzip.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
