; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i32 @llvm.riscv.pmacc.h00.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmacc.h01.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmacc.h11.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmaccu.h00.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmaccu.h01.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmaccu.h11.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmaccsu.h00.i32.v2i16(i32, <2 x i16>, <2 x i16>)
declare i32 @llvm.riscv.pmaccsu.h11.i32.v2i16(i32, <2 x i16>, <2 x i16>)

define i32 @macc_h00(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: macc_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    macc.h00 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmacc.h00.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @macc_h01(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: macc_h01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    macc.h01 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmacc.h01.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @macc_h11(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: macc_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    macc.h11 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmacc.h11.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @maccu_h00(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: maccu_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    maccu.h00 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmaccu.h00.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @maccu_h01(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: maccu_h01:
; RV32P:       # %bb.0:
; RV32P-NEXT:    maccu.h01 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmaccu.h01.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @maccu_h11(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: maccu_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    maccu.h11 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmaccu.h11.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @maccsu_h00(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: maccsu_h00:
; RV32P:       # %bb.0:
; RV32P-NEXT:    maccsu.h00 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmaccsu.h00.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
define i32 @maccsu_h11(i32 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: maccsu_h11:
; RV32P:       # %bb.0:
; RV32P-NEXT:    maccsu.h11 a0, a1, a2
; RV32P-NEXT:    ret
  %r = call i32 @llvm.riscv.pmaccsu.h11.i32.v2i16(i32 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i32 %r
}
