; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pwadda.v4i8(i64, <4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwadda.v2i16(i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwaddau.v4i8(i64, <4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwaddau.v2i16(i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwsuba.v4i8(i64, <4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwsuba.v2i16(i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pwsubau.v4i8(i64, <4 x i8>, <4 x i8>)
declare i64 @llvm.riscv.pwsubau.v2i16(i64, <2 x i16>, <2 x i16>)

define i64 @pwadda_b(i64 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwadda_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwadda.b a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwadda.v4i8(i64 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwadda_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwadda_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwadda.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwadda.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwaddau_b(i64 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwaddau_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwaddau.b a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwaddau.v4i8(i64 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwaddau_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwaddau_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwaddau.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwaddau.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwsuba_b(i64 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwsuba_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsuba.b a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsuba.v4i8(i64 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwsuba_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwsuba_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsuba.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsuba.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pwsubau_b(i64 %rd, <4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pwsubau_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsubau.b a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsubau.v4i8(i64 %rd, <4 x i8> %a, <4 x i8> %b)
  ret i64 %r
}
define i64 @pwsubau_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pwsubau_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pwsubau.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pwsubau.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
