; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <4 x i8>  @llvm.riscv.ppaire.v4i8 (<4 x i8>, <4 x i8>)
declare <4 x i8>  @llvm.riscv.ppaireo.v4i8(<4 x i8>, <4 x i8>)
declare <4 x i8>  @llvm.riscv.ppairoe.v4i8(<4 x i8>, <4 x i8>)
declare <4 x i8>  @llvm.riscv.ppairo.v4i8 (<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.ppaire.v2i16 (<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.ppaireo.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.ppairoe.v2i16(<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.ppairo.v2i16 (<2 x i16>, <2 x i16>)

define <4 x i8> @ppaire_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: ppaire_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    ppaire.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.ppaire.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %r
}

define <4 x i8> @ppaireo_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: ppaireo_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    ppaireo.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.ppaireo.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %r
}

define <4 x i8> @ppairoe_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: ppairoe_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    ppairoe.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.ppairoe.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %r
}

define <4 x i8> @ppairo_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: ppairo_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    ppairo.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.ppairo.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %r
}

define <2 x i16> @ppaire_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: ppaire_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pack a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.ppaire.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @ppaireo_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: ppaireo_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    ppaireo.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.ppaireo.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @ppairoe_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: ppairoe_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    ppairoe.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.ppairoe.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @ppairo_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: ppairo_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    ppairo.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.ppairo.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}
