; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare <4 x i8>  @llvm.riscv.pmseq.v4i8 (<4 x i8>, <4 x i8>)
declare <4 x i8>  @llvm.riscv.pmslt.v4i8 (<4 x i8>, <4 x i8>)
declare <4 x i8>  @llvm.riscv.pmsltu.v4i8(<4 x i8>, <4 x i8>)
declare <2 x i16> @llvm.riscv.pmseq.v2i16 (<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pmslt.v2i16 (<2 x i16>, <2 x i16>)
declare <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16>, <2 x i16>)

define <4 x i8> @pmseq_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmseq_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmseq.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pmseq.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %r
}

define <4 x i8> @pmslt_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmslt_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmslt.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pmslt.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %r
}

define <4 x i8> @pmsltu_b(<4 x i8> %a, <4 x i8> %b) {
; RV32P-LABEL: pmsltu_b:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmsltu.b a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <4 x i8> @llvm.riscv.pmsltu.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %r
}

define <2 x i16> @pmseq_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmseq_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmseq.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmseq.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pmslt_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmslt_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmslt.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmslt.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}

define <2 x i16> @pmsltu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pmsltu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pmsltu.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call <2 x i16> @llvm.riscv.pmsltu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %r
}
