; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <4 x i16> @llvm.riscv.pmhacc.b0.v4i16.v8i8(<4 x i16>, <4 x i16>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmhacc.b1.v4i16.v8i8(<4 x i16>, <4 x i16>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmhaccsu.b0.v4i16.v8i8(<4 x i16>, <4 x i16>, <8 x i8>)
declare <4 x i16> @llvm.riscv.pmhaccsu.b1.v4i16.v8i8(<4 x i16>, <4 x i16>, <8 x i8>)

declare <2 x i32> @llvm.riscv.pmhacc.h0.v2i32.v4i16(<2 x i32>, <2 x i32>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmhacc.h1.v2i32.v4i16(<2 x i32>, <2 x i32>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmhaccsu.h0.v2i32.v4i16(<2 x i32>, <2 x i32>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmhaccsu.h1.v2i32.v4i16(<2 x i32>, <2 x i32>, <4 x i16>)

define <4 x i16> @pmhacc_h_b0(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmhacc_h_b0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhacc.h.b0 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmhacc.b0.v4i16.v8i8(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmhacc_h_b1(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmhacc_h_b1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhacc.h.b1 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmhacc.b1.v4i16.v8i8(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmhaccsu_h_b0(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmhaccsu_h_b0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhaccsu.h.b0 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmhaccsu.b0.v4i16.v8i8(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}
define <4 x i16> @pmhaccsu_h_b1(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b) {
; RV64P-LABEL: pmhaccsu_h_b1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhaccsu.h.b1 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <4 x i16> @llvm.riscv.pmhaccsu.b1.v4i16.v8i8(<4 x i16> %rd, <4 x i16> %a, <8 x i8> %b)
  ret <4 x i16> %r
}

define <2 x i32> @pmhacc_w_h0(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmhacc_w_h0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhacc.w.h0 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmhacc.h0.v2i32.v4i16(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmhacc_w_h1(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmhacc_w_h1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhacc.w.h1 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmhacc.h1.v2i32.v4i16(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmhaccsu_w_h0(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmhaccsu_w_h0:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhaccsu.w.h0 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmhaccsu.h0.v2i32.v4i16(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmhaccsu_w_h1(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b) {
; RV64P-LABEL: pmhaccsu_w_h1:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmhaccsu.w.h1 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmhaccsu.h1.v2i32.v4i16(<2 x i32> %rd, <2 x i32> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
