; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32P

declare i64 @llvm.riscv.pm2wadd.v2i16    (<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2wadda.v2i16   (i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2wadd.x.v2i16  (<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2wadda.x.v2i16 (i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2waddu.v2i16   (<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2waddau.v2i16  (i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2wsub.v2i16    (<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2wsuba.v2i16   (i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2wsub.x.v2i16  (<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2wsuba.x.v2i16 (i64, <2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2waddsu.v2i16  (<2 x i16>, <2 x i16>)
declare i64 @llvm.riscv.pm2waddasu.v2i16 (i64, <2 x i16>, <2 x i16>)

define i64 @pm2wadd_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wadd_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wadd.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wadd.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2wadda_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wadda_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wadda.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wadda.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2wadd_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wadd_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wadd.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wadd.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2wadda_hx(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wadda_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wadda.hx a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wadda.x.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2waddu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2waddu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2waddu.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2waddu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2waddau_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2waddau_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2waddau.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2waddau.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2wsub_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wsub_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wsub.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wsub.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2wsuba_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wsuba_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wsuba.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wsuba.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2wsub_hx(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wsub_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wsub.hx a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wsub.x.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2wsuba_hx(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2wsuba_hx:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2wsuba.hx a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2wsuba.x.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2waddsu_h(<2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2waddsu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2waddsu.h a0, a0, a1
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2waddsu.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
define i64 @pm2waddasu_h(i64 %rd, <2 x i16> %a, <2 x i16> %b) {
; RV32P-LABEL: pm2waddasu_h:
; RV32P:       # %bb.0:
; RV32P-NEXT:    pm2waddasu.h a0, a2, a3
; RV32P-NEXT:    ret
  %r = call i64 @llvm.riscv.pm2waddasu.v2i16(i64 %rd, <2 x i16> %a, <2 x i16> %b)
  ret i64 %r
}
