; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-p -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64P

declare <2 x i32> @llvm.riscv.pmacc.h00.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmacc.h01.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmacc.h11.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmaccu.h00.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmaccu.h01.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmaccu.h11.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmaccsu.h00.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.riscv.pmaccsu.h11.v2i32.v4i16(<2 x i32>, <4 x i16>, <4 x i16>)

declare i64 @llvm.riscv.pmacc.w00.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmacc.w01.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmacc.w11.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmaccu.w00.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmaccu.w01.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmaccu.w11.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmaccsu.w00.i64.v2i32(i64, <2 x i32>, <2 x i32>)
declare i64 @llvm.riscv.pmaccsu.w11.i64.v2i32(i64, <2 x i32>, <2 x i32>)

define <2 x i32> @pmacc_w_h00(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmacc_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmacc.w.h00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmacc.h00.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmacc_w_h01(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmacc_w_h01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmacc.w.h01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmacc.h01.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmacc_w_h11(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmacc_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmacc.w.h11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmacc.h11.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmaccu_w_h00(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmaccu_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmaccu.w.h00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmaccu.h00.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmaccu_w_h01(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmaccu_w_h01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmaccu.w.h01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmaccu.h01.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmaccu_w_h11(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmaccu_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmaccu.w.h11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmaccu.h11.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmaccsu_w_h00(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmaccsu_w_h00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmaccsu.w.h00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmaccsu.h00.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}
define <2 x i32> @pmaccsu_w_h11(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b) {
; RV64P-LABEL: pmaccsu_w_h11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    pmaccsu.w.h11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call <2 x i32> @llvm.riscv.pmaccsu.h11.v2i32.v4i16(<2 x i32> %rd, <4 x i16> %a, <4 x i16> %b)
  ret <2 x i32> %r
}

define i64 @macc_w00(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: macc_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    macc.w00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmacc.w00.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @macc_w01(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: macc_w01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    macc.w01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmacc.w01.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @macc_w11(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: macc_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    macc.w11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmacc.w11.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @maccu_w00(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: maccu_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    maccu.w00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmaccu.w00.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @maccu_w01(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: maccu_w01:
; RV64P:       # %bb.0:
; RV64P-NEXT:    maccu.w01 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmaccu.w01.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @maccu_w11(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: maccu_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    maccu.w11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmaccu.w11.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @maccsu_w00(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: maccsu_w00:
; RV64P:       # %bb.0:
; RV64P-NEXT:    maccsu.w00 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmaccsu.w00.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
define i64 @maccsu_w11(i64 %rd, <2 x i32> %a, <2 x i32> %b) {
; RV64P-LABEL: maccsu_w11:
; RV64P:       # %bb.0:
; RV64P-NEXT:    maccsu.w11 a0, a1, a2
; RV64P-NEXT:    ret
  %r = call i64 @llvm.riscv.pmaccsu.w11.i64.v2i32(i64 %rd, <2 x i32> %a, <2 x i32> %b)
  ret i64 %r
}
